package it.comune.trieste.ouf.udp;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Types;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class CanonicalMaterializer {
  private final JdbcClient db;private final ObjectMapper json;public CanonicalMaterializer(JdbcClient db,ObjectMapper json){this.db=db;this.json=json;}

  @Transactional public Result materialize(String handoffId,UUID urbanObjectId,Map<String,Object> handoff,UdpPorts.MaterializationProfile profile){
    List<Map<String,Object>> old=db.sql("select observation_id,revision_id,material_change,canonical_hash from ouf_udp.materialization_observation where handoff_id=:h").param("h",handoffId).query().listOfRows();if(!old.isEmpty())return new Result((UUID)old.getFirst().get("revision_id"),(Boolean)old.getFirst().get("material_change"),true);
    Map<String,Object> source=HandoffIntakeService.object(handoff,"sourceIdentity"),payload=HandoffIntakeService.object(handoff,"canonicalPayload"),refs=HandoffIntakeService.object(handoff,"contractRefs");String sourceId=HandoffIntakeService.text(source,"sourceId");OffsetDateTime observed=parse(source.get("observedAt"));
    for(UdpPorts.PropertyRule rule:profile.properties()){if(!payload.containsKey(rule.sourceField()))continue;UUID contribution=UUID.randomUUID();Object value=payload.get(rule.sourceField());db.sql("insert into ouf_udp.property_contribution(contribution_id,urban_object_id,handoff_id,property_iri,value_json,value_hash,access_label,source_id,authority_rank,provenance_json,observed_at) values(:i,:u,:h,:p,cast(:v as jsonb),:x,:l,:s,:a,cast(:e as jsonb),:o)").param("i",contribution).param("u",urbanObjectId).param("h",handoffId).param("p",rule.propertyIri()).param("v",write(value)).param("x",hash(value)).param("l",rule.accessLabel()).param("s",sourceId).param("a",rank(rule.authorityOrder(),sourceId)).param("e",write(provenance(handoffId,handoff,rule))).param("o",observed,Types.TIMESTAMP_WITH_TIMEZONE).update();}
    Current current=current(urbanObjectId);Map<String,Object> values=new TreeMap<>(current.values);Map<String,String> labels=new TreeMap<>(current.labels);Map<String,UUID> winners=new TreeMap<>();Map<String,Object> authority=new TreeMap<>(current.authority);
    for(UdpPorts.PropertyRule rule:profile.properties()){List<Map<String,Object>> ranked=db.sql("select contribution_id,value_json::text value_json,value_hash,access_label,source_id,authority_rank from ouf_udp.property_contribution where urban_object_id=:u and property_iri=:p order by authority_rank,observed_at desc nulls last,created_at desc,contribution_id").param("u",urbanObjectId).param("p",rule.propertyIri()).query().listOfRows();if(ranked.isEmpty())continue;Map<String,Map<String,Object>> latestBySource=new LinkedHashMap<>();for(var row:ranked)latestBySource.putIfAbsent(String.valueOf(row.get("source_id")),row);ranked=new ArrayList<>(latestBySource.values());int best=((Number)ranked.getFirst().get("authority_rank")).intValue();List<Map<String,Object>> top=ranked.stream().filter(r->((Number)r.get("authority_rank")).intValue()==best).toList();Set<String> hashes=new HashSet<>();top.forEach(r->hashes.add(String.valueOf(r.get("value_hash"))));if(hashes.size()>1){recordConflict(urbanObjectId,rule.propertyIri(),top,profile.policyRef());continue;}Map<String,Object> winner=top.getFirst();values.put(rule.propertyIri(),readValue(String.valueOf(winner.get("value_json"))));labels.put(rule.propertyIri(),String.valueOf(winner.get("access_label")));winners.put(rule.propertyIri(),(UUID)winner.get("contribution_id"));authority.put(rule.propertyIri(),Map.of("sourceId",winner.get("source_id"),"rank",winner.get("authority_rank"),"valueHash",winner.get("value_hash"),"accessLabel",winner.get("access_label")));}
    String canonicalHash=hash(Map.of("values",values,"labels",labels)),authorityHash=hash(authority);if(canonicalHash.equals(current.canonicalHash)&&authorityHash.equals(current.authorityHash)){observe(handoffId,urbanObjectId,current.revisionId,false,canonicalHash);return new Result(current.revisionId,false,false);}
    UUID revision=UUID.randomUUID();long number=db.sql("select coalesce(max(revision_no),0)+1 from ouf_udp.object_revision where urban_object_id=:u").param("u",urbanObjectId).query(Long.class).single();db.sql("insert into ouf_udp.object_revision(revision_id,urban_object_id,revision_no,canonical_hash,authority_hash,authority_state,canonical_payload,access_labels,source_handoff_id,bundle_ref,semantic_publication_ref,observed_at,valid_from,valid_to) values(:i,:u,:n,:c,:a,cast(:z as jsonb),cast(:p as jsonb),cast(:l as jsonb),:h,:b,:s,:o,:f,:t)").param("i",revision).param("u",urbanObjectId).param("n",number).param("c",canonicalHash).param("a",authorityHash).param("z",write(authority)).param("p",write(values)).param("l",write(labels)).param("h",handoffId).param("b",HandoffIntakeService.text(refs,"bundleRef")).param("s",HandoffIntakeService.text(refs,"semanticPublicationSetRef")).param("o",observed,Types.TIMESTAMP_WITH_TIMEZONE).param("f",parse(source.get("validFrom")),Types.TIMESTAMP_WITH_TIMEZONE).param("t",parse(source.get("validTo")),Types.TIMESTAMP_WITH_TIMEZONE).update();
    for(var entry:winners.entrySet())db.sql("insert into ouf_udp.property_value(property_value_id,revision_id,property_iri,value_json,datatype,access_label,contribution_id) select gen_random_uuid(),:r,:p,value_json,:d,access_label,contribution_id from ouf_udp.property_contribution where contribution_id=:c").param("r",revision).param("p",entry.getKey()).param("d",profile.properties().stream().filter(x->x.propertyIri().equals(entry.getKey())).findFirst().orElseThrow().datatype()).param("c",entry.getValue()).update();
    db.sql("update ouf_udp.urban_object set current_revision_id=:r,revision=:n,updated_at=transaction_timestamp() where urban_object_id=:u").param("r",revision).param("n",number).param("u",urbanObjectId).update();observe(handoffId,urbanObjectId,revision,true,canonicalHash);return new Result(revision,true,false);
  }
  private Current current(UUID object){List<Map<String,Object>> rows=db.sql("select r.revision_id,r.canonical_hash,r.authority_hash,r.authority_state::text authority,r.canonical_payload::text payload,r.access_labels::text labels from ouf_udp.urban_object o join ouf_udp.object_revision r on r.revision_id=o.current_revision_id where o.urban_object_id=:u").param("u",object).query().listOfRows();if(rows.isEmpty())return new Current(null,"","",Map.of(),Map.of(),Map.of());Map<String,Object> r=rows.getFirst();return new Current((UUID)r.get("revision_id"),String.valueOf(r.get("canonical_hash")),String.valueOf(r.get("authority_hash")),readMap(String.valueOf(r.get("authority"))),readMap(String.valueOf(r.get("payload"))),readStringMap(String.valueOf(r.get("labels"))));}
  private void recordConflict(UUID object,String property,List<Map<String,Object>> rows,String policy){List<UUID> ids=rows.stream().map(r->(UUID)r.get("contribution_id")).toList();long exists=db.sql("select count(*) from ouf_udp.property_conflict where urban_object_id=:u and property_iri=:p and state='OPEN'").param("u",object).param("p",property).query(Long.class).single();if(exists==0)db.sql("insert into ouf_udp.property_conflict(conflict_id,urban_object_id,property_iri,contribution_refs,policy_ref) values(gen_random_uuid(),:u,:p,cast(:c as jsonb),:x)").param("u",object).param("p",property).param("c",write(ids)).param("x",policy).update();}
  private void observe(String handoff,UUID object,UUID revision,boolean changed,String hash){db.sql("insert into ouf_udp.materialization_observation(observation_id,handoff_id,urban_object_id,revision_id,material_change,canonical_hash) values(gen_random_uuid(),:h,:u,:r,:m,:c)").param("h",handoff).param("u",object).param("r",revision,Types.OTHER).param("m",changed).param("c",hash).update();}
  private Map<String,Object> provenance(String handoffId,Map<String,Object> handoff,UdpPorts.PropertyRule rule){return Map.of("handoffRef","handoff://"+handoffId,"ingestionRunId",handoff.get("ingestionRunId"),"lineageRef",handoff.get("lineageId"),"sourceIdentity",handoff.get("sourceIdentity"),"rawObjectRef",Objects.toString(handoff.get("rawObjectRef"),""),"contractRefs",handoff.get("contractRefs"),"propertyIri",rule.propertyIri());}
  private static int rank(List<String> order,String source){int i=order.indexOf(source);return i<0?10_000:i;}
  private static OffsetDateTime parse(Object value){return value==null?null:OffsetDateTime.parse(String.valueOf(value));}
  private String hash(Object value){try{return "sha256:"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(json.writeValueAsBytes(canonical(value))));}catch(Exception e){throw new IllegalStateException("UDP_HASH_FAILED",e);}}
  private Object canonical(Object value){if(value instanceof Map<?,?> map){Map<String,Object> sorted=new TreeMap<>();map.forEach((k,v)->sorted.put(String.valueOf(k),canonical(v)));return sorted;}if(value instanceof List<?> list)return list.stream().map(this::canonical).toList();return value;}
  private String write(Object value){try{return json.writeValueAsString(value);}catch(JsonProcessingException e){throw new IllegalArgumentException("UDP_JSON_INVALID",e);}}
  private Object readValue(String value){try{return json.readValue(value,Object.class);}catch(Exception e){throw new IllegalStateException(e);}}
  private Map<String,Object> readMap(String value){try{return json.readValue(value,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}}
  private Map<String,String> readStringMap(String value){try{return json.readValue(value,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}}
  private record Current(UUID revisionId,String canonicalHash,String authorityHash,Map<String,Object> authority,Map<String,Object> values,Map<String,String> labels){}
  public record Result(UUID revisionId,boolean materialChange,boolean duplicate){}
}
