package it.comune.trieste.ouf.udp;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.*;
import java.security.MessageDigest;
import java.sql.Types;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class CanonicalMaterializer {
  private final JdbcClient db;private final ObjectMapper json;public CanonicalMaterializer(JdbcClient db,ObjectMapper json){this.db=db;this.json=json;}
  @Transactional public Result materialize(String handoffId,UUID urbanObjectId,Map<String,Object> handoff,UdpPorts.MaterializationProfile profile){return materialize(handoffId,urbanObjectId,handoff,profile,false);}
  @Transactional public Result applyAuthorityDecision(String handoffId,UUID object,Map<String,Object> handoff,UdpPorts.MaterializationProfile profile){return materialize(handoffId,object,handoff,profile,true);}
  private Result materialize(String handoffId,UUID urbanObjectId,Map<String,Object> handoff,UdpPorts.MaterializationProfile profile,boolean refresh){
    List<Map<String,Object>> old=db.sql("select observation_id,revision_id,material_change from ouf_udp.materialization_observation where handoff_id=:h").param("h",handoffId).query().listOfRows();if(!refresh&&!old.isEmpty())return new Result((UUID)old.getFirst().get("revision_id"),(Boolean)old.getFirst().get("material_change"),true);
    Map<String,Object> change=HandoffIntakeService.object(handoff,"changeRepresentation");String changeFingerprint=fingerprint(change);FastCurrent fast=fastCurrent(urbanObjectId);if(!refresh&&changeFingerprint!=null&&fast!=null&&changeFingerprint.equals(fast.changeFingerprint())){observe(handoffId,urbanObjectId,fast.revisionId(),false,fast.canonicalHash(),changeFingerprint);return new Result(fast.revisionId(),false,false);}
    Map<String,Object> source=HandoffIntakeService.object(handoff,"sourceIdentity"),payload=HandoffIntakeService.object(handoff,"canonicalPayload"),refs=HandoffIntakeService.object(handoff,"contractRefs");String sourceId=HandoffIntakeService.text(source,"sourceId"),mode=HandoffIntakeService.text(change,"mode");OffsetDateTime observed=parse(source.get("observedAt"));Current current=current(urbanObjectId);if(!refresh)validateBase(mode,change,current);
    if(!refresh)contribute(handoffId,urbanObjectId,handoff,profile,payload,sourceId,observed);Map<String,Object> values=new TreeMap<>(current.values);Map<String,String> labels=new TreeMap<>(current.labels);Map<String,UUID> winners=new TreeMap<>();Map<String,Object> authority=new TreeMap<>(current.authority);selectWinners(urbanObjectId,profile,values,labels,winners,authority);
    String canonicalHash=hash(Map.of("values",values,"labels",labels)),authorityHash=hash(authority);if(canonicalHash.equals(current.canonicalHash)&&authorityHash.equals(current.authorityHash)){if(!refresh)observe(handoffId,urbanObjectId,current.revisionId,false,canonicalHash,changeFingerprint);return new Result(current.revisionId,false,false);}
    UUID revision=UUID.randomUUID();long number=db.sql("select coalesce(max(revision_no),0)+1 from ouf_udp.object_revision where urban_object_id=:u").param("u",urbanObjectId).query(Long.class).single();boolean checkpoint=current.revisionId==null||(number-1)%profile.checkpointInterval()==0;Map<String,Object> delta=checkpoint?null:delta(current.values,values);String representation=checkpoint?"FULL_CHECKPOINT":"DELTA_PATCH";
    db.sql("insert into ouf_udp.object_revision(revision_id,urban_object_id,revision_no,canonical_hash,authority_hash,authority_state,canonical_payload,access_labels,source_handoff_id,bundle_ref,semantic_publication_ref,observed_at,valid_from,valid_to,representation,base_revision_id,canonical_delta,change_fingerprint) values(:i,:u,:n,:c,:a,cast(:z as jsonb),cast(:p as jsonb),cast(:l as jsonb),:h,:b,:s,:o,:f,:t,:representation,:base,cast(:delta as jsonb),:fingerprint)")
      .param("i",revision).param("u",urbanObjectId).param("n",number).param("c",canonicalHash).param("a",authorityHash).param("z",write(authority)).param("p",checkpoint?write(values):null,Types.VARCHAR).param("l",write(labels)).param("h",handoffId).param("b",HandoffIntakeService.text(refs,"bundleRef")).param("s",HandoffIntakeService.text(refs,"semanticPublicationSetRef")).param("o",observed,Types.TIMESTAMP_WITH_TIMEZONE).param("f",parse(source.get("validFrom")),Types.TIMESTAMP_WITH_TIMEZONE).param("t",parse(source.get("validTo")),Types.TIMESTAMP_WITH_TIMEZONE).param("representation",representation).param("base",checkpoint?null:current.revisionId,Types.OTHER).param("delta",checkpoint?null:write(delta),Types.VARCHAR).param("fingerprint",changeFingerprint,Types.VARCHAR).update();
    persistValues(revision,winners,profile);bitemporal(profile,urbanObjectId,revision,winners,source);db.sql("insert into ouf_udp.urban_object_current_state(urban_object_id,revision_id,canonical_hash,authority_hash,authority_state,canonical_payload,access_labels,change_fingerprint) values(:u,:r,:c,:a,cast(:z as jsonb),cast(:p as jsonb),cast(:l as jsonb),:f) on conflict(urban_object_id) do update set revision_id=excluded.revision_id,canonical_hash=excluded.canonical_hash,authority_hash=excluded.authority_hash,authority_state=excluded.authority_state,canonical_payload=excluded.canonical_payload,access_labels=excluded.access_labels,change_fingerprint=excluded.change_fingerprint,updated_at=transaction_timestamp()").param("u",urbanObjectId).param("r",revision).param("c",canonicalHash).param("a",authorityHash).param("z",write(authority)).param("p",write(values)).param("l",write(labels)).param("f",changeFingerprint,Types.VARCHAR).update();
    db.sql("update ouf_udp.urban_object set current_revision_id=:r,revision=:n,updated_at=transaction_timestamp() where urban_object_id=:u").param("r",revision).param("n",number).param("u",urbanObjectId).update();if(!refresh)observe(handoffId,urbanObjectId,revision,true,canonicalHash,changeFingerprint);return new Result(revision,true,false);
  }
  private void contribute(String handoff,UUID object,Map<String,Object> envelope,UdpPorts.MaterializationProfile profile,Map<String,Object> payload,String source,OffsetDateTime observed){for(UdpPorts.PropertyRule rule:profile.properties()){if(!payload.containsKey(rule.sourceField()))continue;Object value=payload.get(rule.sourceField());db.sql("insert into ouf_udp.property_contribution(contribution_id,urban_object_id,handoff_id,property_iri,value_json,value_hash,access_label,source_id,authority_rank,provenance_json,observed_at) values(gen_random_uuid(),:u,:h,:p,cast(:v as jsonb),:x,:l,:s,:a,cast(:e as jsonb),:o)").param("u",object).param("h",handoff).param("p",rule.propertyIri()).param("v",write(value)).param("x",hash(value)).param("l",rule.accessLabel()).param("s",source).param("a",rank(rule.authorityOrder(),source)).param("e",write(provenance(handoff,envelope,rule))).param("o",observed,Types.TIMESTAMP_WITH_TIMEZONE).update();}}
  private void selectWinners(UUID object,UdpPorts.MaterializationProfile profile,Map<String,Object> values,Map<String,String> labels,Map<String,UUID> winners,Map<String,Object> authority){for(UdpPorts.PropertyRule rule:profile.properties()){List<Map<String,Object>> top=PropertyEvidence.top(db,object,rule);if(top.isEmpty())continue;Set<String> hashes=new HashSet<>();top.forEach(r->hashes.add(String.valueOf(r.get("value_hash"))));Map<String,Object> human=humanPropertyWinner(object,rule.propertyIri(),profile.policyRef(),top);if(human==null)human=humanGeometryWinner(object,rule.propertyIri(),profile.policyRef(),top);if(hashes.size()>1&&human==null){recordConflict(object,rule.propertyIri(),top,profile);continue;}Map<String,Object> winner=human==null?top.getFirst():human;values.put(rule.propertyIri(),readValue(String.valueOf(winner.get("value_json"))));labels.put(rule.propertyIri(),String.valueOf(winner.get("access_label")));winners.put(rule.propertyIri(),(UUID)winner.get("contribution_id"));authority.put(rule.propertyIri(),Map.of("sourceId",winner.get("source_id"),"rank",winner.get("authority_rank"),"valueHash",winner.get("value_hash"),"accessLabel",winner.get("access_label"),"decisionRef",winner.getOrDefault("human_decision_ref",profile.policyRef())));}}
  private Map<String,Object> humanGeometryWinner(UUID object,String property,String policy,List<Map<String,Object>> candidates){
    if(candidates.size()!=2)return null;
    var choices=db.sql("select d.decision_id,d.chosen_geometry_revision,g1.source_geometry_json::text old_value,g1.access_label old_label,h1.source_id old_source,g2.source_geometry_json::text candidate_value,g2.access_label candidate_label,h2.source_id candidate_source,d.previous_geometry_revision from ouf_udp.human_geometry_decision d join ouf_udp.urban_geometry g1 on g1.geometry_revision_id=d.previous_geometry_revision join ouf_udp.urban_geometry g2 on g2.geometry_revision_id=d.candidate_geometry_revision join ouf_udp.handoff_intake h1 on h1.handoff_id=g1.handoff_id join ouf_udp.handoff_intake h2 on h2.handoff_id=g2.handoff_id where d.urban_object_id=:u and d.property_iri=:property and d.policy_ref=:policy order by d.decided_at desc limit 100")
      .param("u",object).param("property",property).param("policy",policy).query().listOfRows();
    for(var choice:choices){
      Map<String,Object> before=null,after=null;
      for(var candidate:candidates){
        Object value=readValue(String.valueOf(candidate.get("value_json")));
        if(Objects.equals(candidate.get("source_id"),choice.get("old_source"))&&Objects.equals(candidate.get("access_label"),choice.get("old_label"))&&Objects.equals(value,readValue(String.valueOf(choice.get("old_value")))))before=candidate;
        if(Objects.equals(candidate.get("source_id"),choice.get("candidate_source"))&&Objects.equals(candidate.get("access_label"),choice.get("candidate_label"))&&Objects.equals(value,readValue(String.valueOf(choice.get("candidate_value")))))after=candidate;
      }
      if(before!=null&&after!=null&&before!=after){var winner=new LinkedHashMap<>(Objects.equals(choice.get("chosen_geometry_revision"),choice.get("previous_geometry_revision"))?before:after);winner.put("human_decision_ref","geometry-decision://"+choice.get("decision_id"));return winner;}
    }return null;
  }
  private void persistValues(UUID revision,Map<String,UUID> winners,UdpPorts.MaterializationProfile profile){for(var entry:winners.entrySet())db.sql("insert into ouf_udp.property_value(property_value_id,revision_id,property_iri,value_json,datatype,access_label,contribution_id) select gen_random_uuid(),:r,:p,value_json,:d,access_label,contribution_id from ouf_udp.property_contribution where contribution_id=:c").param("r",revision).param("p",entry.getKey()).param("d",profile.properties().stream().filter(x->x.propertyIri().equals(entry.getKey())).findFirst().orElseThrow().datatype()).param("c",entry.getValue()).update();}
  private FastCurrent fastCurrent(UUID object){List<Map<String,Object>> rows=db.sql("select revision_id,canonical_hash,change_fingerprint from ouf_udp.urban_object_current_state where urban_object_id=:u").param("u",object).query().listOfRows();if(rows.isEmpty())return null;var r=rows.getFirst();return new FastCurrent((UUID)r.get("revision_id"),String.valueOf(r.get("canonical_hash")),Objects.toString(r.get("change_fingerprint"),null));}
  private Current current(UUID object){List<Map<String,Object>> rows=db.sql("select revision_id,canonical_hash,authority_hash,authority_state::text authority,canonical_payload::text payload,access_labels::text labels from ouf_udp.urban_object_current_state where urban_object_id=:u").param("u",object).query().listOfRows();if(rows.isEmpty())return new Current(null,"","",Map.of(),Map.of(),Map.of());Map<String,Object> r=rows.getFirst();return new Current((UUID)r.get("revision_id"),String.valueOf(r.get("canonical_hash")),String.valueOf(r.get("authority_hash")),readMap(String.valueOf(r.get("authority"))),readMap(String.valueOf(r.get("payload"))),readStringMap(String.valueOf(r.get("labels"))));}
  private void validateBase(String mode,Map<String,Object> change,Current current){if("FULL_SNAPSHOT".equals(mode))return;if(current.revisionId==null)throw new IllegalStateException("UDP_DELTA_BASE_REQUIRED");Object revision=change.get("baseRevisionRef"),content=change.get("baseContentHash");if(revision!=null&&!Set.of(current.revisionId.toString(),"revision://"+current.revisionId).contains(String.valueOf(revision)))throw new IllegalStateException("UDP_DELTA_BASE_MISMATCH");if(content!=null&&!current.canonicalHash.equals(String.valueOf(content)))throw new IllegalStateException("UDP_DELTA_BASE_MISMATCH");}
  private Map<String,Object> delta(Map<String,Object> before,Map<String,Object> after){Map<String,Object> set=new TreeMap<>();List<String> remove=new ArrayList<>();after.forEach((k,v)->{if(!Objects.equals(before.get(k),v))set.put(k,v);});before.keySet().stream().filter(k->!after.containsKey(k)).sorted().forEach(remove::add);return Map.of("set",set,"remove",remove);}
  private void bitemporal(UdpPorts.MaterializationProfile profile,UUID object,UUID revision,Map<String,UUID> winners,Map<String,Object> source){OffsetDateTime validFrom=parse(source.get("validFrom")),validTo=parse(source.get("validTo"));for(String property:profile.bitemporalProperties()){UUID contribution=winners.get(property);if(contribution==null)continue;String valueHash=db.sql("select value_hash from ouf_udp.property_contribution where contribution_id=:c").param("c",contribution).query(String.class).single();List<Map<String,Object>> open=db.sql("select interval_id,value_hash,valid_from,valid_to from ouf_udp.property_bitemporal_interval where urban_object_id=:u and property_iri=:p and system_to is null for update").param("u",object).param("p",property).query().listOfRows();if(!open.isEmpty()&&valueHash.equals(open.getFirst().get("value_hash"))&&Objects.equals(validFrom,open.getFirst().get("valid_from"))&&Objects.equals(validTo,open.getFirst().get("valid_to")))continue;if(!open.isEmpty())db.sql("update ouf_udp.property_bitemporal_interval set system_to=transaction_timestamp() where interval_id=:i and system_to is null").param("i",open.getFirst().get("interval_id")).update();db.sql("insert into ouf_udp.property_bitemporal_interval(interval_id,urban_object_id,property_iri,revision_id,contribution_id,value_hash,valid_from,valid_to,policy_ref) values(gen_random_uuid(),:u,:p,:r,:c,:h,:f,:t,:policy)").param("u",object).param("p",property).param("r",revision).param("c",contribution).param("h",valueHash).param("f",validFrom,Types.TIMESTAMP_WITH_TIMEZONE).param("t",validTo,Types.TIMESTAMP_WITH_TIMEZONE).param("policy",profile.policyRef()).update();}}
  private void recordConflict(UUID object,String property,List<Map<String,Object>> rows,UdpPorts.MaterializationProfile profile){
    db.sql("insert into ouf_udp.property_conflict(conflict_id,urban_object_id,property_iri,contribution_refs,policy_ref,evidence_hash,materialization_profile) values(gen_random_uuid(),:u,:p,cast(:c as jsonb),:policy,:hash,cast(:profile as jsonb)) on conflict do nothing")
      .param("u",object).param("p",property).param("c",write(rows.stream().map(r->r.get("contribution_id")).toList())).param("policy",profile.policyRef()).param("hash",PropertyEvidence.set(rows)).param("profile",write(profile)).update();
  }
  private Map<String,Object> humanPropertyWinner(UUID object,String property,String policy,List<Map<String,Object>> rows){
    var decisions=db.sql("select decision_id,chosen_evidence_hash from ouf_udp.human_property_decision where urban_object_id=:u and property_iri=:p and policy_ref=:policy and evidence_hash=:hash order by decided_at desc limit 1")
      .param("u",object).param("p",property).param("policy",policy).param("hash",PropertyEvidence.set(rows)).query().listOfRows();
    if(decisions.isEmpty())return null;
    var d=decisions.getFirst();for(var row:rows)if(PropertyEvidence.item(row).equals(d.get("chosen_evidence_hash"))){var winner=new LinkedHashMap<>(row);winner.put("human_decision_ref","property-decision://"+d.get("decision_id"));return winner;}
    return null;
  }
  private void observe(String handoff,UUID object,UUID revision,boolean changed,String hash,String fingerprint){db.sql("insert into ouf_udp.materialization_observation(observation_id,handoff_id,urban_object_id,revision_id,material_change,canonical_hash,change_fingerprint) values(gen_random_uuid(),:h,:u,:r,:m,:c,:f)").param("h",handoff).param("u",object).param("r",revision,Types.OTHER).param("m",changed).param("c",hash).param("f",fingerprint,Types.VARCHAR).update();}
  private String fingerprint(Map<String,Object> change){List<String> fields=List.of("canonicalContentHash","geometryHash","relationshipsHash","contractEvidenceHash");if(fields.stream().anyMatch(x->change.get(x)==null||String.valueOf(change.get(x)).isBlank()))return null;Map<String,Object> parts=new TreeMap<>();fields.forEach(x->parts.put(x,change.get(x)));return hash(parts);}
  private Map<String,Object> provenance(String handoff,Map<String,Object> envelope,UdpPorts.PropertyRule rule){return Map.of("handoffRef","handoff://"+handoff,"ingestionRunId",envelope.get("ingestionRunId"),"lineageRef",envelope.get("lineageId"),"sourceIdentity",envelope.get("sourceIdentity"),"rawObjectRef",Objects.toString(envelope.get("rawObjectRef"),""),"contractRefs",envelope.get("contractRefs"),"propertyIri",rule.propertyIri());}
  private static int rank(List<String> order,String source){int i=order.indexOf(source);return i<0?10_000:i;}private static OffsetDateTime parse(Object value){return value==null?null:OffsetDateTime.parse(String.valueOf(value));}
  private String hash(Object value){try{return "sha256:"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(json.writeValueAsBytes(canonical(value))));}catch(Exception e){throw new IllegalStateException("UDP_HASH_FAILED",e);}}
  private Object canonical(Object value){if(value instanceof Map<?,?> map){Map<String,Object> sorted=new TreeMap<>();map.forEach((k,v)->sorted.put(String.valueOf(k),canonical(v)));return sorted;}if(value instanceof List<?> list)return list.stream().map(this::canonical).toList();return value;}
  private String write(Object value){try{return json.writeValueAsString(value);}catch(JsonProcessingException e){throw new IllegalArgumentException("UDP_JSON_INVALID",e);}}private Object readValue(String value){try{return json.readValue(value,Object.class);}catch(Exception e){throw new IllegalStateException(e);}}private Map<String,Object> readMap(String value){try{return json.readValue(value,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}}private Map<String,String> readStringMap(String value){try{return json.readValue(value,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}}
  private record FastCurrent(UUID revisionId,String canonicalHash,String changeFingerprint){}private record Current(UUID revisionId,String canonicalHash,String authorityHash,Map<String,Object> authority,Map<String,Object> values,Map<String,String> labels){}public record Result(UUID revisionId,boolean materialChange,boolean duplicate){}
}
