package it.comune.trieste.ouf.udp;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;
import java.sql.Types;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class GovernedServingService {
  private final JdbcClient db;private final ObjectMapper json;public GovernedServingService(JdbcClient db,ObjectMapper json){this.db=db;this.json=json;}

  @Transactional public Map<String,Object> current(UUID id,ServingAuthorizationContext auth){auth.require("urban.object.read");Map<String,Object> object=object(id,auth);auth.requireResource("urban.object.read","object",id,"OPEN",Map.of("canonicalType",String.valueOf(object.get("canonical_type"))));UUID revision=(UUID)object.get("current_revision_id");Map<String,Object> out=identity(object);if(revision!=null){out.put("revisionId",revision);out.put("properties",properties(id,revision,"urban.object.read",auth));geometry(id,out,auth);}return out;}
  @Transactional public Page<Map<String,Object>> history(UUID id,int requested,String cursor,OffsetDateTime asOf,ServingAuthorizationContext auth){auth.require("urban.object.history.read");object(id,auth);auth.requireResource("urban.object.history.read","object",id,"OPEN",Map.of());int size=size(requested,100);long before=decodeLong(cursor,Long.MAX_VALUE);var spec=db.sql("select revision_id,revision_no,recorded_at,valid_from,valid_to from ouf_udp.object_revision where urban_object_id=:u and revision_no<:b and (cast(:a as timestamptz) is null or recorded_at<=cast(:a as timestamptz)) order by revision_no desc limit :l").param("u",id).param("b",before).param("a",asOf,Types.TIMESTAMP_WITH_TIMEZONE).param("l",size+1);List<Map<String,Object>> rows=spec.query().listOfRows();boolean more=rows.size()>size;if(more)rows=rows.subList(0,size);List<Map<String,Object>> result=new ArrayList<>();for(var row:rows){Map<String,Object> item=new LinkedHashMap<>(row);item.put("properties",properties(id,(UUID)row.get("revision_id"),"urban.object.history.read",auth));result.add(item);}String next=more?encode(((Number)rows.getLast().get("revision_no")).longValue()):null;return new Page<>(result,next);}
  @Transactional public Page<Map<String,Object>> search(String type,int requested,String cursor,ServingAuthorizationContext auth){auth.require("urban.object.search");if(type==null||type.isBlank()||type.contains("%")||type.contains("*"))throw new IllegalArgumentException("UDP_INDEXED_TYPE_FILTER_REQUIRED");int size=size(requested,100);UUID after=decodeUuid(cursor);var spec=db.sql("select urban_object_id,canonical_type,status,current_revision_id,revision from ouf_udp.urban_object where tenant_id=:t and canonical_type=:c and status='ACTIVE' and (cast(:a as uuid) is null or urban_object_id>cast(:a as uuid)) order by urban_object_id limit :l").param("t",auth.tenantId()).param("c",type).param("a",after,Types.OTHER).param("l",size+1);List<Map<String,Object>> rows=spec.query().listOfRows();boolean more=rows.size()>size;if(more)rows=rows.subList(0,size);List<Map<String,Object>> result=new ArrayList<>();for(var row:rows){if(!auth.permits("urban.object.search","object",row.get("urban_object_id"),"OPEN",Map.of("canonicalType",String.valueOf(row.get("canonical_type")))))continue;Map<String,Object> item=identity(row);UUID rev=(UUID)row.get("current_revision_id");if(rev!=null)item.put("properties",properties((UUID)row.get("urban_object_id"),rev,"urban.object.search",auth));result.add(item);}return new Page<>(result,more&&result.size()==rows.size()?encode(rows.getLast().get("urban_object_id").toString()):null,result.size()!=rows.size());}
  @Transactional public Page<Map<String,Object>> relationships(UUID id,int requested,String cursor,ServingAuthorizationContext auth){auth.require("urban.relationship.read");object(id,auth);int size=size(requested,100);if(auth.allowedDataLabels().isEmpty())return new Page<>(List.of(),null);UUID after=decodeUuid(cursor);List<Map<String,Object>> rows=db.sql("select r.relationship_id,r.source_object_id,r.relation_iri,r.target_object_id,v.access_label,h.source_id as _policy_source,h.ingestion_run_id as _policy_job from ouf_udp.urban_relationship r join ouf_udp.relationship_revision v on v.relationship_revision_id=r.current_revision_id join ouf_udp.relationship_contribution rc on rc.contribution_id=v.contribution_id join ouf_udp.handoff_intake h on h.handoff_id=rc.handoff_id join ouf_udp.urban_object target on target.urban_object_id=r.target_object_id where r.source_object_id=:u and r.status='ACTIVE' and target.tenant_id=:t and v.access_label in (:labels) and (cast(:a as uuid) is null or r.relationship_id>cast(:a as uuid)) order by r.relationship_id limit :l").param("u",id).param("t",auth.tenantId()).param("labels",auth.allowedDataLabels()).param("a",after,Types.OTHER).param("l",size+1).query().listOfRows();boolean more=rows.size()>size;if(more)rows=rows.subList(0,size);List<Map<String,Object>> visible=new ArrayList<>();for(var row:rows){
    if(!auth.permits("urban.relationship.read","relationship",row.get("relationship_id"),String.valueOf(row.get("access_label")),dataScope(row,Map.of("sourceObjectRef",id.toString(),"targetObjectRef",row.get("target_object_id").toString(),"relationIri",String.valueOf(row.get("relation_iri"))))))continue;
    if(!auth.permits("urban.object.read","object",row.get("target_object_id"),"OPEN",Map.of())){audit(auth,"urban.object.read","object://"+row.get("target_object_id"),"OPEN","REDACTED");continue;}
    var projection=new LinkedHashMap<>(row);projection.remove("_policy_source");projection.remove("_policy_job");visible.add(projection);
  }String next=more&&visible.size()==rows.size()?encode(rows.getLast().get("relationship_id").toString()):null;return new Page<>(visible,next,visible.size()!=rows.size());}
  @Transactional public List<Map<String,Object>> lineage(UUID id,String property,ServingAuthorizationContext auth){auth.require(property==null?"lineage.object.read":"lineage.property.read");object(id,auth);if(auth.allowedDataLabels().isEmpty())return List.of();var spec=db.sql("select property_iri,access_label,source_id,provenance_json::text provenance,created_at from ouf_udp.property_contribution where urban_object_id=:u and (cast(:p as text) is null or property_iri=cast(:p as text)) and access_label in (:labels) order by created_at desc limit 200").param("u",id).param("p",property,Types.VARCHAR).param("labels",auth.allowedDataLabels());List<Map<String,Object>> out=new ArrayList<>();for(var row:spec.query().listOfRows()){String label=row.get("access_label") instanceof String value?value:null;var scope=Map.of("propertyIri",String.valueOf(row.get("property_iri")),"sourceRef",String.valueOf(row.get("source_id")));
    if(!auth.permits(property==null?"lineage.object.read":"lineage.property.read","object",id,label,scope)){audit(auth,property==null?"lineage.object.read":"lineage.property.read","lineage://"+id+"/"+row.get("property_iri"),label,"REDACTED");continue;}
    Map<String,Object> provenance=read(String.valueOf(row.get("provenance")));Map<String,Object> item=new LinkedHashMap<>();item.put("propertyIri",row.get("property_iri"));item.put("accessLabel",label);item.put("handoffRef",provenance.get("handoffRef"));item.put("lineageRef",provenance.get("lineageRef"));item.put("contractRefs",provenance.get("contractRefs"));if(auth.permits("lineage.source.read","object",id,label,scope))item.put("sourceIdentity",provenance.get("sourceIdentity"));if(auth.permits("lineage.raw.read","object",id,label,scope))item.put("rawObjectRef",provenance.get("rawObjectRef"));out.add(item);}return out;}
  private Map<String,Object> object(UUID id,ServingAuthorizationContext auth){return db.sql("select urban_object_id,canonical_type,status,current_revision_id,revision,redirect_to from ouf_udp.urban_object where urban_object_id=:i and tenant_id=:t").param("i",id).param("t",auth.tenantId()).query().listOfRows().stream().findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"UDP_OBJECT_NOT_VISIBLE"));}
  private Map<String,Object> properties(UUID objectId,UUID revision,String capability,ServingAuthorizationContext auth){Map<String,Object> out=new LinkedHashMap<>();List<Map<String,Object>> rows=db.sql("select p.property_iri,p.value_json::text value,p.access_label,c.source_id as _policy_source,h.ingestion_run_id as _policy_job from ouf_udp.property_value p join ouf_udp.property_contribution c on c.contribution_id=p.contribution_id join ouf_udp.handoff_intake h on h.handoff_id=c.handoff_id where p.revision_id=:r order by p.property_iri").param("r",revision).query().listOfRows();for(var row:rows){String label=row.get("access_label") instanceof String value?value:null;if(auth.permits(capability,"object",objectId,label,dataScope(row,Map.of("propertyIri",String.valueOf(row.get("property_iri")),"revisionRef",revision.toString()))))out.put(String.valueOf(row.get("property_iri")),readAny(String.valueOf(row.get("value"))));else audit(auth,capability,"object://"+objectId+"/property/"+row.get("property_iri"),label,"REDACTED");}return out;}
  private void geometry(UUID id,Map<String,Object> out,ServingAuthorizationContext auth){List<Map<String,Object>> rows=db.sql("select ST_AsGeoJSON(g.geometry) geojson,ST_AsGeoJSON(coalesce(g.canonical_geometry,g.geometry),15,0) canonical_geojson,g.canonical_srid,g.source_crs,g.evidence_json::text transformation,g.access_label,h.source_id as _policy_source,h.ingestion_run_id as _policy_job from ouf_udp.urban_geometry_current c join ouf_udp.urban_geometry g on g.geometry_revision_id=c.geometry_revision_id join ouf_udp.handoff_intake h on h.handoff_id=g.handoff_id where c.urban_object_id=:u").param("u",id).query().listOfRows();if(rows.isEmpty())return;String label=rows.getFirst().get("access_label") instanceof String value?value:null;if(auth.permits("urban.geometry.read","object",id,label,dataScope(rows.getFirst(),Map.of("projection","geometry")))){var row=rows.getFirst();out.put("geometry",readAny(String.valueOf(row.get("geojson"))));out.put("geometryCrs","EPSG:4326");out.put("canonicalGeometry",Map.of("crs","EPSG:"+row.get("canonical_srid"),"axisOrder","XY","geoJson",readAny(String.valueOf(row.get("canonical_geojson")))));out.put("geometryProvenance",readAny(String.valueOf(row.get("transformation"))));}else audit(auth,"urban.geometry.read","geometry://"+id,label,"REDACTED");}
  private static Map<String,String> dataScope(Map<String,Object> row,Map<String,String> base){var scope=new HashMap<>(base);if(row.get("_policy_source")!=null)scope.put("sourceRef",row.get("_policy_source").toString());if(row.get("_policy_job")!=null)scope.put("jobRef",row.get("_policy_job").toString());return scope;}
  private static Map<String,Object> identity(Map<String,Object> row){Map<String,Object> out=new LinkedHashMap<>();out.put("urbanObjectId",row.get("urban_object_id"));out.put("canonicalType",row.get("canonical_type"));out.put("status",row.get("status"));out.put("revision",row.get("revision"));if(row.get("redirect_to")!=null)out.put("redirectTo",row.get("redirect_to"));return out;}
  private void audit(ServingAuthorizationContext auth,String capability,String resource,String label,String outcome){db.sql("insert into ouf_udp.serving_access_audit(audit_id,principal_type,principal_subject,tenant_id,capability,resource_ref,classification,outcome,authorization_decision_ref,correlation_id) values(gen_random_uuid(),:p,:s,:t,:c,:r,:l,:o,:d,:x)").param("p",auth.principalType()).param("s",auth.subject()).param("t",auth.tenantId()).param("c",capability).param("r",resource).param("l",label==null?"UNRESOLVED":label).param("o",outcome).param("d",auth.decisionRef(capability)).param("x",auth.correlationId()).update();}
  private static int size(int n,int max){if(n<1||n>max)throw new IllegalArgumentException("UDP_PAGE_SIZE_OUT_OF_RANGE");return n;}private static String encode(String value){return Base64.getUrlEncoder().withoutPadding().encodeToString(value.getBytes(StandardCharsets.UTF_8));}private static String encode(long value){return encode(Long.toString(value));}private static String decode(String cursor){try{return new String(Base64.getUrlDecoder().decode(cursor),StandardCharsets.UTF_8);}catch(Exception e){throw new IllegalArgumentException("UDP_CURSOR_INVALID");}}private static long decodeLong(String cursor,long fallback){return cursor==null?fallback:Long.parseLong(decode(cursor));}private static UUID decodeUuid(String cursor){return cursor==null?null:UUID.fromString(decode(cursor));}
  private Map<String,Object> read(String v){try{return json.readValue(v,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}}private Object readAny(String v){try{return json.readValue(v,Object.class);}catch(Exception e){throw new IllegalStateException(e);}}
  public record Page<T>(List<T> items,String nextCursor,boolean partial){public Page(List<T> items,String nextCursor){this(items,nextCursor,false);}public Page{items=List.copyOf(items);}}
}
