package it.comune.trieste.ouf.udp;

import java.sql.Types;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class GraphQueryService {
  private final JdbcClient db;private final QueryBudgetStore budgets;private final CapabilityRouter router;public GraphQueryService(JdbcClient db,QueryBudgetStore budgets,CapabilityRouter router){this.db=db;this.budgets=budgets;this.router=router;}
  @Transactional public GraphResult neighbors(UUID start,List<String> relationTypes,int maxNodes,int maxEdges,ServingAuthorizationContext auth){auth.require("urban.graph.neighbors");ensureVisible(start,auth);validate(relationTypes,maxNodes,maxEdges,200,500);budgets.consume(auth,"GRAPH",1,maxNodes,maxEdges,estimateBytes(maxNodes,maxEdges),2000);timeout();List<Edge> edges=queryOneHop(start,relationTypes,maxEdges,auth);Set<UUID> nodes=new LinkedHashSet<>();nodes.add(start);for(var e:edges){nodes.add(e.source());nodes.add(e.target());if(nodes.size()>maxNodes)throw new IllegalArgumentException("UDP_GRAPH_NODE_LIMIT");}return new GraphResult(nodes.stream().toList(),edges,false,"INDEXED_ADJACENCY");}
  @Transactional public GraphResult traverse(UUID start,List<String> relationTypes,int maxDepth,int maxNodes,int maxEdges,CapabilityRouter.TraversalPurpose purpose,ServingAuthorizationContext auth){router.authorizeTraverse(purpose,auth);if(maxDepth<1||maxDepth>4)throw new IllegalArgumentException("UDP_GRAPH_DEPTH_OUT_OF_RANGE");validate(relationTypes,maxNodes,maxEdges,500,1000);ensureVisible(start,auth);budgets.consume(auth,"GRAPH",1,maxNodes,maxEdges,estimateBytes(maxNodes,maxEdges),2000);timeout();if(auth.allowedDataLabels().isEmpty())return new GraphResult(List.of(start),List.of(),false,"BOUNDED_RECURSIVE_CTE");List<Map<String,Object>> rows=db.sql("with recursive walk(source_id,relation_iri,target_id,relationship_id,depth,path) as (select r.source_object_id,r.relation_iri,r.target_object_id,r.relationship_id,1,array[r.source_object_id,r.target_object_id] from ouf_udp.urban_relationship r join ouf_udp.relationship_revision v on v.relationship_revision_id=r.current_revision_id join ouf_udp.urban_object t on t.urban_object_id=r.target_object_id where r.source_object_id=:s and r.status='ACTIVE' and r.relation_iri in (:relations) and v.access_label in (:labels) and t.tenant_id=:tenant union all select r.source_object_id,r.relation_iri,r.target_object_id,r.relationship_id,w.depth+1,w.path||r.target_object_id from walk w join ouf_udp.urban_relationship r on r.source_object_id=w.target_id join ouf_udp.relationship_revision v on v.relationship_revision_id=r.current_revision_id join ouf_udp.urban_object t on t.urban_object_id=r.target_object_id where w.depth<:depth and r.status='ACTIVE' and r.relation_iri in (:relations) and v.access_label in (:labels) and t.tenant_id=:tenant and not r.target_object_id=any(w.path)) select source_id,relation_iri,target_id,relationship_id,depth from walk order by depth,relationship_id limit :limit").param("s",start).param("relations",relationTypes).param("labels",auth.allowedDataLabels()).param("tenant",auth.tenantId()).param("depth",maxDepth).param("limit",maxEdges+1).query().listOfRows();boolean truncated=rows.size()>maxEdges;if(truncated)rows=rows.subList(0,maxEdges);List<Edge> edges=new ArrayList<>();Set<UUID> nodes=new LinkedHashSet<>();nodes.add(start);for(var r:rows){Edge e=new Edge((UUID)r.get("relationship_id"),(UUID)r.get("source_id"),String.valueOf(r.get("relation_iri")),(UUID)r.get("target_id"),((Number)r.get("depth")).intValue());edges.add(e);nodes.add(e.source());nodes.add(e.target());if(nodes.size()>maxNodes)throw new IllegalArgumentException("UDP_GRAPH_NODE_LIMIT");}return new GraphResult(nodes.stream().toList(),edges,truncated,"BOUNDED_RECURSIVE_CTE");}
  private void ensureVisible(UUID start,ServingAuthorizationContext auth){long visible=db.sql("select count(*) from ouf_udp.urban_object where urban_object_id=:id and tenant_id=:tenant").param("id",start).param("tenant",auth.tenantId()).query(Long.class).single();if(visible==0)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"UDP_OBJECT_NOT_VISIBLE");}
  private List<Edge> queryOneHop(UUID start,List<String> relations,int max,ServingAuthorizationContext auth){if(auth.allowedDataLabels().isEmpty())return List.of();return db.sql("select r.relationship_id,r.source_object_id,r.relation_iri,r.target_object_id from ouf_udp.urban_relationship r join ouf_udp.relationship_revision v on v.relationship_revision_id=r.current_revision_id join ouf_udp.urban_object t on t.urban_object_id=r.target_object_id where r.source_object_id=:s and r.status='ACTIVE' and r.relation_iri in (:r) and v.access_label in (:l) and t.tenant_id=:t order by r.relationship_id limit :m").param("s",start).param("r",relations).param("l",auth.allowedDataLabels()).param("t",auth.tenantId()).param("m",max).query((rs,n)->new Edge(rs.getObject("relationship_id",UUID.class),rs.getObject("source_object_id",UUID.class),rs.getString("relation_iri"),rs.getObject("target_object_id",UUID.class),1)).list();}
  private void timeout(){db.sql("set local statement_timeout='2000ms'").update();}
  private static void validate(List<String> relations,int nodes,int edges,int maxNodes,int maxEdges){if(relations==null||relations.isEmpty()||relations.size()>20||relations.stream().anyMatch(x->x==null||x.isBlank()||x.contains("*")))throw new IllegalArgumentException("UDP_GRAPH_RELATION_ALLOWLIST_REQUIRED");if(nodes<1||nodes>maxNodes||edges<1||edges>maxEdges)throw new IllegalArgumentException("UDP_GRAPH_LIMIT_OUT_OF_RANGE");}
  private static long estimateBytes(int nodes,int edges){return nodes*128L+edges*256L;}
  public record Edge(UUID relationshipId,UUID source,String relationIri,UUID target,int depth){}
  public record GraphResult(List<UUID> nodes,List<Edge> edges,boolean truncated,String physicalPlan){public GraphResult{nodes=List.copyOf(nodes);edges=List.copyOf(edges);}}
}
