package it.comune.trieste.ouf.udp;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Types;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class IdentityGovernanceService {
  private final JdbcClient db;private final ObjectMapper json;
  public IdentityGovernanceService(JdbcClient db,ObjectMapper json){this.db=db;this.json=json;}

  @Transactional(readOnly=true) public Map<String,Object> mergeImpact(UUID survivor,UUID merged){requireActive(survivor);requireActive(merged);if(survivor.equals(merged))throw new IllegalArgumentException("UDP_MERGE_SAME_OBJECT");Map<String,Object> impact=new LinkedHashMap<>();impact.put("survivorObjectId",survivor);impact.put("mergedObjectId",merged);impact.put("bindingsToMove",count("select count(*) from ouf_udp.source_binding where urban_object_id=:u",merged));impact.put("propertiesToReevaluate",count("select count(distinct property_iri) from ouf_udp.property_contribution where urban_object_id in(:a,:b)",survivor,merged));impact.put("relationshipsToRepoint",count("select count(*) from ouf_udp.urban_relationship where status='ACTIVE' and (source_object_id=:u or target_object_id=:u)",merged));impact.put("potentialDuplicateEdges",db.sql("select count(*) from ouf_udp.urban_relationship x join ouf_udp.urban_relationship y on y.source_object_id=:s and x.source_object_id=:m and y.relation_iri=x.relation_iri and y.target_object_id=x.target_object_id and y.status='ACTIVE' and x.status='ACTIVE'").param("s",survivor).param("m",merged).query(Long.class).single());impact.put("geometryDistanceMeters",geometryDistance(survivor,merged));impact.put("deprecatedObjectIds",List.of(merged));return impact;}

  @Transactional public Plan planMerge(UUID survivor,UUID merged,TrustedHumanContext actor){actor.require("urban.merge.plan");Map<String,Object> proposal=Map.of("survivorObjectId",survivor,"mergedObjectId",merged);return createPlan("MERGE",List.of(survivor,merged),proposal,mergeImpact(survivor,merged),actor);}

  @Transactional public Plan executeMerge(UUID planId,long expectedVersion,String reason,String idempotencyKey,TrustedHumanContext actor){actor.require("urban.object.merge");validateDecision(reason,idempotencyKey);Plan replay=idempotent(planId,idempotencyKey);if(replay!=null)return replay;Map<String,Object> plan=lockPlan(planId,"MERGE",expectedVersion);Map<String,Object> proposal=read(String.valueOf(plan.get("proposal")));UUID survivor=UUID.fromString(String.valueOf(proposal.get("survivorObjectId"))),merged=UUID.fromString(String.valueOf(proposal.get("mergedObjectId")));requireActive(survivor);requireActive(merged);
    db.sql("insert into ouf_udp.source_binding_history(history_id,source_id,type_code,source_object_id,previous_urban_object_id,new_urban_object_id,disposition,plan_id) select gen_random_uuid(),source_id,type_code,source_object_id,urban_object_id,:s,'REALLOCATED',:p from ouf_udp.source_binding where urban_object_id=:m and state='ACTIVE'").param("s",survivor).param("p",planId).param("m",merged).update();db.sql("update ouf_udp.source_binding set urban_object_id=:s where urban_object_id=:m and state='ACTIVE'").param("s",survivor).param("m",merged).update();
    db.sql("insert into ouf_udp.relationship_identity_history(history_id,relationship_id,previous_source_object_id,previous_target_object_id,disposition,plan_id) select gen_random_uuid(),relationship_id,source_object_id,target_object_id,'REPOINTED',:p from ouf_udp.urban_relationship where status='ACTIVE' and (source_object_id=:m or target_object_id=:m)").param("p",planId).param("m",merged).update();db.sql("update ouf_udp.urban_relationship set status='SUPERSEDED' where status='ACTIVE' and (source_object_id=:m or target_object_id=:m)").param("m",merged).update();
    db.sql("update ouf_udp.urban_object set status='MERGED',redirect_to=:s,revision=revision+1,updated_at=transaction_timestamp() where urban_object_id=:m").param("s",survivor).param("m",merged).update();db.sql("insert into ouf_udp.object_identity_history(history_id,object_id,transition,successor_ids,plan_id,decision_ref) values(gen_random_uuid(),:m,'MERGED',cast(:s as jsonb),:p,:d)").param("m",merged).param("s",write(List.of(survivor))).param("p",planId).param("d",actor.authorizationDecisionRef()).update();finish(planId,expectedVersion,reason,idempotencyKey,actor,"UDP_OBJECT_MERGED");return getPlan(planId);}

  @Transactional(readOnly=true) public Map<String,Object> splitImpact(UUID original,List<UUID> successors,Map<String,String> allocations){requireActive(original);if(successors.size()<2||new HashSet<>(successors).size()!=successors.size())throw new IllegalArgumentException("UDP_SPLIT_SUCCESSORS_INVALID");successors.forEach(this::requireActive);List<String> bindings=db.sql("select source_id||'|'||type_code||'|'||source_object_id from ouf_udp.source_binding where urban_object_id=:u order by 1").param("u",original).query(String.class).list();if(!allocations.keySet().containsAll(bindings))throw new IllegalArgumentException("UDP_SPLIT_BINDING_ALLOCATION_INCOMPLETE");for(String value:allocations.values())if(!"UNRESOLVED".equals(value)&&successors.stream().noneMatch(x->x.toString().equals(value)))throw new IllegalArgumentException("UDP_SPLIT_ALLOCATION_TARGET_INVALID");Map<String,Object> impact=new LinkedHashMap<>();impact.put("originalObjectId",original);impact.put("successorObjectIds",successors);impact.put("bindings",bindings.size());impact.put("unresolvedBindings",allocations.values().stream().filter("UNRESOLVED"::equals).count());impact.put("relationshipsRequiringReview",count("select count(*) from ouf_udp.urban_relationship where status='ACTIVE' and (source_object_id=:u or target_object_id=:u)",original));impact.put("propertyCopyPolicy","RECOMPUTE_FROM_CONTRIBUTIONS");impact.put("edgePolicy","REVIEW_REQUIRED_NO_AUTOMATIC_DUPLICATION");return impact;}

  @Transactional public Plan planSplit(UUID original,List<UUID> successors,Map<String,String> allocations,TrustedHumanContext actor){actor.require("urban.split.plan");Map<String,Object> proposal=new LinkedHashMap<>();proposal.put("originalObjectId",original);proposal.put("successorObjectIds",successors);proposal.put("bindingAllocations",allocations);return createPlan("SPLIT",concat(original,successors),proposal,splitImpact(original,successors,allocations),actor);}

  @Transactional public Plan executeSplit(UUID planId,long expectedVersion,String reason,String idempotencyKey,TrustedHumanContext actor){actor.require("urban.object.split");validateDecision(reason,idempotencyKey);Plan replay=idempotent(planId,idempotencyKey);if(replay!=null)return replay;Map<String,Object> plan=lockPlan(planId,"SPLIT",expectedVersion);Map<String,Object> proposal=read(String.valueOf(plan.get("proposal")));UUID original=UUID.fromString(String.valueOf(proposal.get("originalObjectId")));List<UUID> successors=((List<?>)proposal.get("successorObjectIds")).stream().map(x->UUID.fromString(String.valueOf(x))).toList();Map<String,String> allocations=stringMap(proposal.get("bindingAllocations"));splitImpact(original,successors,allocations);
    List<Map<String,Object>> bindings=db.sql("select source_id,type_code,source_object_id,urban_object_id from ouf_udp.source_binding where urban_object_id=:u and state='ACTIVE' for update").param("u",original).query().listOfRows();for(var b:bindings){String key=b.get("source_id")+"|"+b.get("type_code")+"|"+b.get("source_object_id"),choice=allocations.get(key);if("UNRESOLVED".equals(choice)){history(b,null,"UNRESOLVED",planId);db.sql("update ouf_udp.source_binding set state='UNRESOLVED' where source_id=:s and type_code=:c and source_object_id=:o").param("s",b.get("source_id")).param("c",b.get("type_code")).param("o",b.get("source_object_id")).update();db.sql("insert into ouf_udp.split_resolution_issue(issue_id,plan_id,issue_type,resource_ref,evidence_json) values(gen_random_uuid(),:p,'BINDING_UNRESOLVED',:r,cast(:e as jsonb))").param("p",planId).param("r","source-binding://"+key).param("e",write(Map.of("previousObjectId",original))).update();}else{UUID target=UUID.fromString(choice);history(b,target,"REALLOCATED",planId);db.sql("update ouf_udp.source_binding set urban_object_id=:t where source_id=:s and type_code=:c and source_object_id=:o").param("t",target).param("s",b.get("source_id")).param("c",b.get("type_code")).param("o",b.get("source_object_id")).update();}}
    List<Map<String,Object>> edges=db.sql("select relationship_id,source_object_id,target_object_id,relation_iri from ouf_udp.urban_relationship where status='ACTIVE' and (source_object_id=:u or target_object_id=:u)").param("u",original).query().listOfRows();for(var e:edges){db.sql("insert into ouf_udp.relationship_identity_history(history_id,relationship_id,previous_source_object_id,previous_target_object_id,disposition,plan_id) values(gen_random_uuid(),:r,:s,:t,'REVIEW_REQUIRED',:p)").param("r",e.get("relationship_id")).param("s",e.get("source_object_id")).param("t",e.get("target_object_id")).param("p",planId).update();db.sql("insert into ouf_udp.split_resolution_issue(issue_id,plan_id,issue_type,resource_ref,evidence_json) values(gen_random_uuid(),:p,'RELATIONSHIP_REVIEW_REQUIRED',:r,cast(:e as jsonb))").param("p",planId).param("r","relationship://"+e.get("relationship_id")).param("e",write(Map.of("relationIri",e.get("relation_iri"),"successorCandidates",successors))).update();}
    db.sql("update ouf_udp.urban_object set status='SPLIT',revision=revision+1,updated_at=transaction_timestamp() where urban_object_id=:u").param("u",original).update();db.sql("insert into ouf_udp.object_identity_history(history_id,object_id,transition,successor_ids,plan_id,decision_ref) values(gen_random_uuid(),:u,'SPLIT',cast(:s as jsonb),:p,:d)").param("u",original).param("s",write(successors)).param("p",planId).param("d",actor.authorizationDecisionRef()).update();finish(planId,expectedVersion,reason,idempotencyKey,actor,"UDP_OBJECT_SPLIT");return getPlan(planId);}

  @Transactional public void decideResolutionIssue(UUID issueId,long expectedVersion,String action,String reason,UUID target,TrustedHumanContext actor){actor.require("resolution.match.approve");if(reason==null||reason.isBlank())throw new IllegalArgumentException("UDP_REASON_REQUIRED");boolean approve="APPROVE".equals(action);if(!approve&&!"DISMISS".equals(action))throw new IllegalArgumentException("UDP_ISSUE_ACTION_INVALID");Map<String,Object> issue=db.sql("select i.handoff_id,i.candidate_refs::text candidates,h.source_id,h.type_code,h.source_object_id from ouf_udp.resolution_issue i join ouf_udp.handoff_intake h on h.handoff_id=i.handoff_id where i.issue_id=:i and i.state='OPEN' and i.version=:v for update").param("i",issueId).param("v",expectedVersion).query().listOfRows().stream().findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.CONFLICT,"UDP_ISSUE_VERSION_CONFLICT"));if(approve){if(target==null||!String.valueOf(issue.get("candidates")).contains(target.toString()))throw new IllegalArgumentException("UDP_TARGET_NOT_A_CANDIDATE");db.sql("insert into ouf_udp.source_binding(source_id,type_code,source_object_id,urban_object_id,first_handoff_id) values(:s,:t,:o,:u,:h) on conflict(source_id,type_code,source_object_id) do update set urban_object_id=excluded.urban_object_id,state='ACTIVE' where source_binding.state='UNRESOLVED'").param("s",issue.get("source_id")).param("t",issue.get("type_code")).param("o",issue.get("source_object_id")).param("u",target).param("h",issue.get("handoff_id")).update();}String state=approve?"RESOLVED":"DISMISSED",decisionAction=approve?"APPROVE_MATCH":"DISMISS",evidence=hash(Map.of("issueId",issueId,"target",Objects.toString(target,"")));db.sql("insert into ouf_udp.human_resolution_decision(decision_id,issue_id,action,target_urban_object_id,actor_subject,authorization_decision_ref,reason,evidence_hash) values(gen_random_uuid(),:i,:x,:t,:a,:d,:r,:e)").param("i",issueId).param("x",decisionAction).param("t",target,Types.OTHER).param("a",actor.subject()).param("d",actor.authorizationDecisionRef()).param("r",reason).param("e",evidence).update();db.sql("update ouf_udp.resolution_issue set state=:s,version=version+1,resolved_at=transaction_timestamp(),resolved_by_subject=:a,resolution_reason=:r,authorization_decision_ref=:d where issue_id=:i and version=:v").param("s",state).param("a",actor.subject()).param("r",reason).param("d",actor.authorizationDecisionRef()).param("i",issueId).param("v",expectedVersion).update();audit(decisionAction,null,actor,reason,evidence);}

  @Transactional(readOnly=true) public Map<String,Object> resolveIdentity(UUID id){Map<String,Object> source=db.sql("select urban_object_id,status,redirect_to,current_revision_id,revision from ouf_udp.urban_object where urban_object_id=:i").param("i",id).query().listOfRows().stream().findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"UDP_OBJECT_NOT_FOUND"));Map<String,Object> row=new LinkedHashMap<>(source);if("SPLIT".equals(row.get("status")))row.put("successorIds",db.sql("select successor_ids::text from ouf_udp.object_identity_history where object_id=:i order by occurred_at desc limit 1").param("i",id).query(String.class).list().stream().findFirst().map(this::read).orElse(Map.of()));return row;}
  @Transactional(readOnly=true) public Plan getPlan(UUID id){return db.sql("select plan_id,action,state,version,impact_json::text impact,proposal_json::text proposal from ouf_udp.governance_plan where plan_id=:i").param("i",id).query((rs,n)->new Plan(rs.getObject("plan_id",UUID.class),rs.getString("action"),rs.getString("state"),rs.getLong("version"),read(rs.getString("impact")),read(rs.getString("proposal")))).list().stream().findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"UDP_PLAN_NOT_FOUND"));}
  private Plan createPlan(String action,List<UUID> subjects,Map<String,Object> proposal,Map<String,Object> impact,TrustedHumanContext actor){UUID id=UUID.randomUUID();db.sql("insert into ouf_udp.governance_plan(plan_id,action,subject_object_ids,proposal_json,impact_json,created_by_subject) values(:i,:a,cast(:s as jsonb),cast(:p as jsonb),cast(:m as jsonb),:u)").param("i",id).param("a",action).param("s",write(subjects)).param("p",write(proposal)).param("m",write(impact)).param("u",actor.subject()).update();audit("UDP_"+action+"_PLANNED",id,actor,null,hash(impact));return getPlan(id);}
  private Plan idempotent(UUID planId,String key){List<UUID> rows=db.sql("select plan_id from ouf_udp.governance_plan where idempotency_key=:k").param("k",key).query(UUID.class).list();if(rows.isEmpty())return null;if(!rows.getFirst().equals(planId))throw new ResponseStatusException(HttpStatus.CONFLICT,"UDP_IDEMPOTENCY_KEY_CONFLICT");return getPlan(planId);}
  private Map<String,Object> lockPlan(UUID id,String action,long version){List<Map<String,Object>> rows=db.sql("select plan_id,action,state,version,proposal_json::text proposal from ouf_udp.governance_plan where plan_id=:i for update").param("i",id).query().listOfRows();if(rows.isEmpty())throw new ResponseStatusException(HttpStatus.NOT_FOUND,"UDP_PLAN_NOT_FOUND");Map<String,Object> p=rows.getFirst();if(!action.equals(p.get("action")))throw new IllegalArgumentException("UDP_PLAN_ACTION_MISMATCH");if(((Number)p.get("version")).longValue()!=version)throw new ResponseStatusException(HttpStatus.CONFLICT,"UDP_PLAN_VERSION_CONFLICT");return p;}
  private void finish(UUID id,long version,String reason,String key,TrustedHumanContext actor,String action){int n=db.sql("update ouf_udp.governance_plan set state='EXECUTED',version=version+1,executed_at=transaction_timestamp(),decision_ref=:d,reason=:r,idempotency_key=:k where plan_id=:i and state='DRAFT' and version=:v").param("d",actor.authorizationDecisionRef()).param("r",reason).param("k",key).param("i",id).param("v",version).update();if(n!=1)throw new ResponseStatusException(HttpStatus.CONFLICT,"UDP_PLAN_VERSION_CONFLICT");audit(action,id,actor,reason,hash(Map.of("planId",id,"decisionRef",actor.authorizationDecisionRef())));}
  private void audit(String action,UUID plan,TrustedHumanContext actor,String reason,String evidence){db.sql("insert into ouf_udp.governance_audit(audit_id,action,outcome,plan_id,actor_type,actor_subject,tenant_id,capability,authorization_decision_ref,reason,correlation_id,evidence_hash) values(gen_random_uuid(),:a,'ALLOWED',:p,:t,:s,:n,:c,:d,:r,:x,:e)").param("a",action).param("p",plan,Types.OTHER).param("t",actor.actorType()).param("s",actor.subject()).param("n",actor.tenantId()).param("c",actor.capabilities().stream().sorted().findFirst().orElse("")).param("d",actor.authorizationDecisionRef()).param("r",reason,Types.VARCHAR).param("x",actor.correlationId()).param("e",evidence).update();}
  private void history(Map<String,Object> b,UUID target,String disposition,UUID plan){db.sql("insert into ouf_udp.source_binding_history(history_id,source_id,type_code,source_object_id,previous_urban_object_id,new_urban_object_id,disposition,plan_id) values(gen_random_uuid(),:s,:t,:o,:p,:n,:d,:i)").param("s",b.get("source_id")).param("t",b.get("type_code")).param("o",b.get("source_object_id")).param("p",b.get("urban_object_id")).param("n",target,Types.OTHER).param("d",disposition).param("i",plan).update();}
  private void requireActive(UUID id){String status=db.sql("select status from ouf_udp.urban_object where urban_object_id=:i").param("i",id).query(String.class).list().stream().findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"UDP_OBJECT_NOT_FOUND"));if(!"ACTIVE".equals(status))throw new IllegalArgumentException("UDP_OBJECT_NOT_ACTIVE");}
  private long count(String sql,UUID a){return db.sql(sql).param("u",a).query(Long.class).single();}private long count(String sql,UUID a,UUID b){return db.sql(sql).param("a",a).param("b",b).query(Long.class).single();}
  private Double geometryDistance(UUID a,UUID b){List<Double> x=db.sql("select ST_Distance(a.geometry::geography,b.geometry::geography) from ouf_udp.urban_geometry_current ac join ouf_udp.urban_geometry a on a.geometry_revision_id=ac.geometry_revision_id join ouf_udp.urban_geometry_current bc on bc.urban_object_id=:b join ouf_udp.urban_geometry b on b.geometry_revision_id=bc.geometry_revision_id where ac.urban_object_id=:a").param("a",a).param("b",b).query(Double.class).list();return x.isEmpty()?null:x.getFirst();}
  private static void validateDecision(String reason,String key){if(reason==null||reason.isBlank())throw new IllegalArgumentException("UDP_REASON_REQUIRED");if(key==null||key.isBlank())throw new IllegalArgumentException("UDP_IDEMPOTENCY_KEY_REQUIRED");}
  private Plan plan(Map<String,Object> p){return getPlan((UUID)p.get("plan_id"));}private static List<UUID> concat(UUID first,List<UUID> rest){List<UUID> out=new ArrayList<>();out.add(first);out.addAll(rest);return out;}
  @SuppressWarnings("unchecked") private Map<String,Object> read(String v){try{return json.readValue(v,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException(e);}}@SuppressWarnings("unchecked") private static Map<String,String> stringMap(Object v){Map<String,String> out=new LinkedHashMap<>();((Map<String,Object>)v).forEach((k,x)->out.put(k,String.valueOf(x)));return out;}
  private String write(Object v){try{return json.writeValueAsString(v);}catch(JsonProcessingException e){throw new IllegalArgumentException("UDP_JSON_INVALID",e);}}private String hash(Object v){try{return "sha256:"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(json.writeValueAsBytes(v)));}catch(Exception e){throw new IllegalStateException(e);}}
  public record Plan(UUID planId,String action,String state,long version,Map<String,Object> impact,Map<String,Object> proposal){}
}
