package it.comune.trieste.ouf.udp;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service
public class LakeLifecycleService {
  private final LakeCatalogRepository catalog;private final ObjectProvider<LakeObjectStoragePort> storageProvider;
  public LakeLifecycleService(LakeCatalogRepository catalog,ObjectProvider<LakeObjectStoragePort> storageProvider){this.catalog=catalog;this.storageProvider=storageProvider;}

  public LakeCatalogRepository.LakeObject store(byte[] content,String tenant,String source,String type,String tier,String mediaType,String retentionClass,String accessLabel,OffsetDateTime retentionUntil,String correlation){validate(tier,retentionClass,retentionUntil);String hash=hash(content),key="lake/"+tenant+"/"+tier.toLowerCase(Locale.ROOT)+"/"+hash.substring(7);UUID id=UUID.randomUUID();var staged=catalog.stage(id,tenant,source,type,tier,hash,mediaType,content.length,key,retentionClass,accessLabel,retentionUntil,correlation);if("VERIFIED".equals(staged.state()))return staged;if(!"STAGED".equals(staged.state()))throw new IllegalStateException("UDP_LAKE_DUPLICATE_NOT_USABLE");try{var receipt=storage().put(key,content,mediaType,hash);if(!receipt.durable()||!key.equals(receipt.locator())||!hash.equals(receipt.contentHash())||receipt.sizeBytes()!=content.length)throw new IllegalStateException("UDP_LAKE_DURABILITY_PROOF_INVALID");var durable=catalog.transition(staged.id(),staged.version(),"STAGED","DURABLE","SYSTEM","",correlation,Map.of("locatorFingerprint",fingerprint(receipt.locator())));var head=storage().head(receipt.locator()).orElseThrow(()->new IllegalStateException("UDP_LAKE_OBJECT_MISSING_AFTER_PUT"));if(!hash.equals(head.contentHash())||head.sizeBytes()!=content.length)throw new IllegalStateException("UDP_LAKE_CHECKSUM_MISMATCH");return catalog.transition(durable.id(),durable.version(),"DURABLE","VERIFIED","SYSTEM","",correlation,Map.of("locatorFingerprint",fingerprint(receipt.locator())));}catch(RuntimeException failure){LakeCatalogRepository.LakeObject current=catalog.get(staged.id());if("STAGED".equals(current.state()))catalog.transition(current.id(),current.version(),"STAGED","FAILED","SYSTEM","",correlation,Map.of("safeErrorCode","UDP_LAKE_WRITE_FAILED"));else if("DURABLE".equals(current.state()))catalog.transition(current.id(),current.version(),"DURABLE","QUARANTINED","SYSTEM","",correlation,Map.of("safeErrorCode","UDP_LAKE_VERIFY_FAILED"));throw failure;}}

  public LakeCatalogRepository.LakeObject authorizeDeletion(UUID id,long expected,String reason,TrustedHumanContext actor){if(reason==null||reason.isBlank())throw new IllegalArgumentException("UDP_LAKE_DELETION_REASON_REQUIRED");return catalog.requestDeletion(id,expected,OffsetDateTime.now().plusHours(1),reason,actor);}

  public int purge(String worker,int limit,String correlation){int completed=0;for(var object:catalog.claimPurge(worker,Math.min(Math.max(limit,1),100))){String locator=object.previousLocator()!=null?object.previousLocator():object.locator();storage().delete(locator);catalog.completePurge(object.id(),worker,object.leaseGeneration(),object.version(),correlation);completed++;}return completed;}

  public UUID compact(List<UUID> inputIds,String correlation){if(inputIds==null||inputIds.size()<2||inputIds.size()>100)throw new IllegalArgumentException("UDP_COMPACTION_INPUT_LIMIT");List<LakeCatalogRepository.LakeObject> inputs=inputIds.stream().distinct().map(catalog::get).toList();if(inputs.size()!=inputIds.size())throw new IllegalArgumentException("UDP_COMPACTION_DUPLICATE_INPUT");var first=inputs.getFirst();if(inputs.stream().anyMatch(x->!"VERIFIED".equals(x.state())||!x.tenant().equals(first.tenant())||!x.tier().equals(first.tier())||!x.retentionClass().equals(first.retentionClass())||!x.accessLabel().equals(first.accessLabel())))throw new IllegalArgumentException("UDP_COMPACTION_BOUNDARY_VIOLATION");long total=inputs.stream().mapToLong(LakeCatalogRepository.LakeObject::size).sum();if(total>67_108_864L)throw new IllegalArgumentException("UDP_COMPACTION_SIZE_LIMIT");ByteArrayOutputStream packed=new ByteArrayOutputStream((int)total);for(var input:inputs)packed.writeBytes(storage().read(input.locator()));var output=store(packed.toByteArray(),first.tenant(),"compaction",first.type(),first.tier(),"application/vnd.ouf.compaction-pack",first.retentionClass(),first.accessLabel(),inputs.stream().map(LakeCatalogRepository.LakeObject::retentionUntil).max(Comparator.naturalOrder()).orElseThrow(),correlation);UUID manifest=UUID.randomUUID();catalog.finalizeCompaction(manifest,first.tenant(),output.id(),output.hash(),inputs,correlation);return manifest;}

  public ScanResult reconcile(){UUID scan=UUID.randomUUID();Map<String,LakeObjectStoragePort.StoredObject> inventory=new HashMap<>();for(var stored:storage().inventory())inventory.put(stored.locator(),stored);Set<String> referenced=new HashSet<>();int missing=0,mismatch=0,orphan=0;for(var object:catalog.active()){if("COMPACTED".equals(object.state())){if(object.previousLocator()!=null)referenced.add(object.previousLocator());continue;}referenced.add(object.locator());var actual=inventory.get(object.locator());if(actual==null){catalog.finding(scan,"MISSING_OBJECT","CRITICAL",object.id(),fingerprint(object.locator()),Map.of("state",object.state()));quarantine(object,"UDP_LAKE_MISSING",scan.toString());missing++;}else if(!object.hash().equals(actual.contentHash())||object.size()!=actual.sizeBytes()){catalog.finding(scan,"CHECKSUM_MISMATCH","CRITICAL",object.id(),fingerprint(object.locator()),Map.of("state",object.state()));quarantine(object,"UDP_LAKE_CHECKSUM_MISMATCH",scan.toString());mismatch++;}}for(var stored:inventory.values())if(!referenced.contains(stored.locator())){catalog.finding(scan,"ORPHAN_STORAGE","HIGH",null,fingerprint(stored.locator()),Map.of("sizeBytes",stored.sizeBytes()));orphan++;}return new ScanResult(scan,missing,mismatch,orphan);}

  private void quarantine(LakeCatalogRepository.LakeObject object,String code,String correlation){if(Set.of("DURABLE","VERIFIED","COMPACTED","COLD").contains(object.state()))catalog.transition(object.id(),object.version(),object.state(),"QUARANTINED","SYSTEM","",correlation,Map.of("safeErrorCode",code));}
  private LakeObjectStoragePort storage(){LakeObjectStoragePort port=storageProvider.getIfAvailable();if(port==null)throw new ResponseStatusException(HttpStatus.SERVICE_UNAVAILABLE,"UDP_LAKE_STORAGE_UNAVAILABLE");return port;}
  private static void validate(String tier,String retention,OffsetDateTime until){if(!Set.of("RAW","NORMALIZED","CURATED","EXPORT").contains(tier)||!Set.of("OPERATIONAL","AUDIT","ARCHIVAL","LEGAL_HOLD","DERIVED_REBUILDABLE").contains(retention)||until==null)throw new IllegalArgumentException("UDP_LAKE_POLICY_INVALID");}
  private static String hash(byte[] bytes){try{return "sha256:"+HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes));}catch(Exception e){throw new IllegalStateException(e);}}
  private static String fingerprint(String locator){return hash(locator.getBytes(StandardCharsets.UTF_8));}
  public record ScanResult(UUID scanId,int missing,int checksumMismatch,int orphan){}
}
