package it.comune.trieste.ouf.udp;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.OffsetDateTime;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

@Repository
public class LakeCatalogRepository {
  private final JdbcClient db;private final ObjectMapper json;
  public LakeCatalogRepository(JdbcClient db,ObjectMapper json){this.db=db;this.json=json;}

  @Transactional public LakeObject stage(UUID id,String tenant,String source,String type,String tier,String hash,String mediaType,long size,String locator,String retentionClass,String label,OffsetDateTime retentionUntil,String correlation){int inserted=db.sql("insert into ouf_udp.lake_object(lake_object_id,tenant_id,source_id,type_code,tier,content_hash,media_type,logical_size_bytes,locator,state,retention_class,access_label,retention_until) values(:id,:tenant,:source,:type,:tier,:hash,:media,:size,:locator,'STAGED',:retention,:label,:until) on conflict(tenant_id,tier,content_hash,source_id,type_code) do nothing").param("id",id).param("tenant",tenant).param("source",source).param("type",type).param("tier",tier).param("hash",hash).param("media",mediaType).param("size",size).param("locator",locator).param("retention",retentionClass).param("label",label).param("until",retentionUntil).update();LakeObject result=inserted==1?get(id):find(tenant,tier,hash,source,type);if(inserted==1)event(id,null,"STAGED","SYSTEM","",correlation,"LAKE_OBJECT_STAGED",Map.of());return result;}
  @Transactional public LakeObject transition(UUID id,long expected,String from,String to,String actor,String decision,String correlation,Map<String,Object> detail){int n=db.sql("update ouf_udp.lake_object set state=:to,state_version=state_version+1,verified_at=case when :to='VERIFIED' then transaction_timestamp() else verified_at end,deleted_at=case when :to='DELETED' then transaction_timestamp() else deleted_at end where lake_object_id=:id and state=:from and state_version=:version").param("to",to).param("id",id).param("from",from).param("version",expected).update();if(n!=1)throw new IllegalStateException("UDP_LAKE_STATE_CONFLICT");event(id,from,to,actor,decision,correlation,"LAKE_OBJECT_STATE_CHANGED",detail);return get(id);}
  @Transactional public LakeObject requestDeletion(UUID id,long expected,OffsetDateTime purgeAfter,String reason,TrustedHumanContext actor){actor.require("lake.object.delete");int n=db.sql("update ouf_udp.lake_object set state='DELETION_PENDING',purge_after=:purge,state_version=state_version+1 where lake_object_id=:id and tenant_id=:tenant and state in('VERIFIED','COMPACTED','COLD','QUARANTINED') and state_version=:version and retention_until<=transaction_timestamp() and legal_hold=false and retention_class<>'LEGAL_HOLD' and blocking_lineage_refs=0 and historical_replay_required=false and active_export_refs=0").param("purge",purgeAfter).param("id",id).param("tenant",actor.tenantId()).param("version",expected).update();if(n!=1)throw new IllegalStateException("UDP_LAKE_DELETION_GUARD_DENIED");event(id,null,"DELETION_PENDING",actor.subject(),actor.authorizationDecisionRef(),actor.correlationId(),"LAKE_OBJECT_DELETION_AUTHORIZED",Map.of("purgeAfter",purgeAfter.toString(),"reason",reason));return get(id);}
  @Transactional public LakeObject markCompacted(UUID id,long expected,String newLocator,UUID manifest,String correlation){LakeObject before=get(id);int n=db.sql("update ouf_udp.lake_object set state='COMPACTED',previous_locator=locator,locator=:locator,state_version=state_version+1 where lake_object_id=:id and state='VERIFIED' and state_version=:version").param("locator",newLocator).param("id",id).param("version",expected).update();if(n!=1)throw new IllegalStateException("UDP_LAKE_COMPACTION_CONFLICT");event(id,before.state(),"COMPACTED","SYSTEM","",correlation,"LAKE_OBJECT_COMPACTED",Map.of("manifestId",manifest.toString()));return get(id);}
  @Transactional public void manifest(UUID manifest,String tenant,UUID output,String hash,List<LakeObject> inputs,String correlation){db.sql("insert into ouf_udp.compaction_manifest(manifest_id,tenant_id,output_lake_object_id,output_content_hash,state,verified_at) values(:id,:tenant,:output,:hash,'VERIFIED',transaction_timestamp())").param("id",manifest).param("tenant",tenant).param("output",output).param("hash",hash).update();long offset=0;for(LakeObject input:inputs){db.sql("insert into ouf_udp.compaction_manifest_entry(manifest_id,input_lake_object_id,logical_offset,logical_length) values(:m,:i,:o,:l)").param("m",manifest).param("i",input.id()).param("o",offset).param("l",input.size()).update();offset+=input.size();}}
  @Transactional public void finalizeCompaction(UUID manifest,String tenant,UUID output,String hash,List<LakeObject> inputs,String correlation){manifest(manifest,tenant,output,hash,inputs,correlation);String logical="manifest://"+manifest;for(LakeObject input:inputs){int n=db.sql("update ouf_udp.lake_object set state='COMPACTED',previous_locator=locator,locator=:locator,state_version=state_version+1 where lake_object_id=:id and state='VERIFIED' and state_version=:version").param("locator",logical).param("id",input.id()).param("version",input.version()).update();if(n!=1)throw new IllegalStateException("UDP_LAKE_COMPACTION_CONFLICT");event(input.id(),"VERIFIED","COMPACTED","SYSTEM","",correlation,"LAKE_OBJECT_COMPACTED",Map.of("manifestId",manifest.toString()));}}
  @Transactional public UUID finding(UUID scan,String type,String severity,UUID lakeObject,String fingerprint,Map<String,Object> evidence){UUID id=UUID.randomUUID();db.sql("insert into ouf_udp.storage_reconciliation_finding(finding_id,finding_type,severity,lake_object_id,locator_fingerprint,safe_evidence,scan_id) values(:id,:type,:severity,:object,:fingerprint,cast(:e as jsonb),:scan)").param("id",id).param("type",type).param("severity",severity).param("object",lakeObject).param("fingerprint",fingerprint).param("e",write(evidence)).param("scan",scan).update();return id;}
  public LakeObject get(UUID id){return db.sql("select * from ouf_udp.lake_object where lake_object_id=:id").param("id",id).query((rs,n)->map(rs)).single();}
  public List<LakeObject> active(){return db.sql("select * from ouf_udp.lake_object where state in('DURABLE','VERIFIED','COMPACTED','COLD','QUARANTINED','DELETION_PENDING') order by lake_object_id").query((rs,n)->map(rs)).list();}
  @Transactional public List<LakeObject> claimPurge(String owner,int limit){return db.sql("with candidates as(select lake_object_id from ouf_udp.lake_object where state='DELETION_PENDING' and purge_after<=transaction_timestamp() and (lease_until is null or lease_until<transaction_timestamp()) order by purge_after,lake_object_id limit :limit for update skip locked) update ouf_udp.lake_object o set lease_owner=:owner,lease_until=transaction_timestamp()+interval '5 minutes',lease_generation=lease_generation+1,state_version=state_version+1 from candidates c where o.lake_object_id=c.lake_object_id returning o.*").param("owner",owner).param("limit",limit).query((rs,n)->map(rs)).list();}
  @Transactional public LakeObject completePurge(UUID id,String owner,long generation,long expected,String correlation){int n=db.sql("update ouf_udp.lake_object set state='DELETED',deleted_at=transaction_timestamp(),lease_owner=null,lease_until=null,state_version=state_version+1 where lake_object_id=:id and state='DELETION_PENDING' and lease_owner=:owner and lease_generation=:generation and state_version=:version").param("id",id).param("owner",owner).param("generation",generation).param("version",expected).update();if(n!=1)throw new IllegalStateException("UDP_LAKE_PURGE_LEASE_LOST");event(id,"DELETION_PENDING","DELETED","SYSTEM","",correlation,"LAKE_OBJECT_PURGED",Map.of());return get(id);}
  private LakeObject find(String tenant,String tier,String hash,String source,String type){return db.sql("select * from ouf_udp.lake_object where tenant_id=:tenant and tier=:tier and content_hash=:hash and source_id=:source and type_code=:type").param("tenant",tenant).param("tier",tier).param("hash",hash).param("source",source).param("type",type).query((rs,n)->map(rs)).single();}
  private LakeObject map(java.sql.ResultSet rs)throws java.sql.SQLException{return new LakeObject(rs.getObject("lake_object_id",UUID.class),rs.getString("tenant_id"),rs.getString("source_id"),rs.getString("type_code"),rs.getString("tier"),rs.getString("content_hash"),rs.getString("media_type"),rs.getLong("logical_size_bytes"),rs.getString("locator"),rs.getString("previous_locator"),rs.getString("state"),rs.getString("retention_class"),rs.getString("access_label"),rs.getObject("retention_until",OffsetDateTime.class),rs.getBoolean("legal_hold"),rs.getInt("blocking_lineage_refs"),rs.getBoolean("historical_replay_required"),rs.getInt("active_export_refs"),rs.getObject("purge_after",OffsetDateTime.class),rs.getString("lease_owner"),rs.getLong("lease_generation"),rs.getLong("state_version"));}
  private void event(UUID id,String from,String to,String actor,String decision,String correlation,String type,Map<String,Object> detail){db.sql("insert into ouf_udp.lake_object_event(event_id,lake_object_id,event_type,from_state,to_state,actor_subject,authorization_decision_ref,correlation_id,safe_detail) values(gen_random_uuid(),:id,:type,:from,:to,:actor,:decision,:correlation,cast(:detail as jsonb))").param("id",id).param("type",type).param("from",from).param("to",to).param("actor",actor).param("decision",decision).param("correlation",correlation).param("detail",write(detail)).update();}
  private String write(Object value){try{return json.writeValueAsString(value);}catch(JsonProcessingException e){throw new IllegalArgumentException("UDP_JSON_INVALID",e);}}
  public record LakeObject(UUID id,String tenant,String source,String type,String tier,String hash,String mediaType,long size,String locator,String previousLocator,String state,String retentionClass,String accessLabel,OffsetDateTime retentionUntil,boolean legalHold,int blockingLineageRefs,boolean historicalReplayRequired,int activeExportRefs,OffsetDateTime purgeAfter,String leaseOwner,long leaseGeneration,long version){}
}
