package it.comune.trieste.ouf.udp;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.Duration;
import java.util.*;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

@Repository
public class ResolutionRepository {
  private final JdbcClient db;private final ObjectMapper json;public ResolutionRepository(JdbcClient db,ObjectMapper json){this.db=db;this.json=json;}
  @Transactional public Optional<Claim> claim(String worker,Duration lease){
    return db.sql("with candidate as (select job_id from ouf_udp.materialization_job where state='READY' or (state='RUNNING' and lease_until<transaction_timestamp()) or (state='PAUSED' and next_integrity_check_at<=transaction_timestamp()) order by created_at for update skip locked limit 1) update ouf_udp.materialization_job j set state='RUNNING',state_version=state_version+1,claimed_by=:w,lease_until=transaction_timestamp()+(:m*interval '1 millisecond'),attempts=attempts+1,updated_at=transaction_timestamp() from candidate c,ouf_udp.handoff_intake h where j.job_id=c.job_id and h.handoff_id=j.handoff_id returning j.job_id,j.handoff_id,h.type_code,h.payload_json::text,j.integrity_baseline_hash,j.integrity_attempts")
      .param("w",worker).param("m",lease.toMillis()).query((r,n)->new Claim(r.getObject(1,UUID.class),r.getString(2),r.getString(3),read(r.getString(4)),worker,r.getString(5),r.getInt(6))).optional();
  }
  @Transactional public void integrityPassed(Claim claim,String baselineHash){int n=db.sql("update ouf_udp.materialization_job set integrity_baseline_hash=:hash,missing_ref_hashes='[]'::jsonb,integrity_checked_at=transaction_timestamp(),next_integrity_check_at=null,safe_failure_code=null,updated_at=transaction_timestamp() where job_id=:j and state='RUNNING' and claimed_by=:w").param("hash",baselineHash).param("j",claim.jobId()).param("w",claim.worker()).update();if(n!=1)throw new IllegalStateException("UDP_RESOLUTION_LEASE_LOST");event(claim.handoffId(),"REFERENCE_INTEGRITY_PASSED",Map.of("baselineHash",baselineHash));}
  @Transactional public void pause(Claim claim,List<String> missing,long delayMillis,int maxAttempts){int next=claim.integrityAttempts()+1;String state=next>=maxAttempts?"QUARANTINED":"PAUSED";int n=db.sql("update ouf_udp.materialization_job set state=:state,state_version=state_version+1,claimed_by=null,lease_until=null,missing_ref_hashes=cast(:missing as jsonb),integrity_attempts=:attempts,integrity_checked_at=transaction_timestamp(),next_integrity_check_at=case when :state='PAUSED' then transaction_timestamp()+(:delay*interval '1 millisecond') else null end,safe_failure_code='UDP_REFERENCE_INTEGRITY_MISSING',updated_at=transaction_timestamp() where job_id=:j and state='RUNNING' and claimed_by=:w").param("state",state).param("missing",write(missing)).param("attempts",next).param("delay",delayMillis).param("j",claim.jobId()).param("w",claim.worker()).update();if(n!=1)throw new IllegalStateException("UDP_RESOLUTION_LEASE_LOST");event(claim.handoffId(),"PAUSED".equals(state)?"REFERENCE_INTEGRITY_PAUSED":"REFERENCE_INTEGRITY_QUARANTINED",Map.of("missingRefHashes",missing,"integrityAttempt",next));}
  @Transactional public void quarantine(Claim claim,String code){String safe=safe(code);int n=db.sql("update ouf_udp.materialization_job set state='QUARANTINED',state_version=state_version+1,claimed_by=null,lease_until=null,integrity_attempts=integrity_attempts+1,integrity_checked_at=transaction_timestamp(),next_integrity_check_at=null,safe_failure_code=:code,updated_at=transaction_timestamp() where job_id=:j and state='RUNNING' and claimed_by=:w").param("code",safe).param("j",claim.jobId()).param("w",claim.worker()).update();if(n!=1)throw new IllegalStateException("UDP_RESOLUTION_LEASE_LOST");event(claim.handoffId(),"REFERENCE_INTEGRITY_QUARANTINED",Map.of("safeFailureCode",safe));}
  @Transactional public void awaitValidity(Claim claim,java.time.OffsetDateTime validFrom){
    int n=db.sql("update ouf_udp.materialization_job set state='PAUSED',state_version=state_version+1,claimed_by=null,lease_until=null,next_integrity_check_at=:at,safe_failure_code='UDP_GEOMETRY_NOT_YET_VALID',updated_at=transaction_timestamp() where job_id=:j and state='RUNNING' and claimed_by=:w").param("at",validFrom).param("j",claim.jobId()).param("w",claim.worker()).update();
    if(n!=1)throw new IllegalStateException("UDP_RESOLUTION_LEASE_LOST");event(claim.handoffId(),"GEOMETRY_VALIDITY_DEFERRED",Map.of("validFrom",validFrom.toString()));
  }
  @Transactional public void complete(Claim claim){int n=db.sql("update ouf_udp.materialization_job set state='SUCCEEDED',state_version=state_version+1,claimed_by=null,lease_until=null,updated_at=transaction_timestamp() where job_id=:j and state='RUNNING' and claimed_by=:w").param("j",claim.jobId()).param("w",claim.worker()).update();if(n!=1)throw new IllegalStateException("UDP_RESOLUTION_LEASE_LOST");db.sql("update ouf_udp.handoff_intake set state='PROCESSED',processed_at=transaction_timestamp() where handoff_id=:h and state in('DURABLE','PROCESSING')").param("h",claim.handoffId()).update();event(claim.handoffId(),"RESOLUTION_COMPLETED",Map.of());}
  @Transactional public void fail(Claim claim,String safeCode){db.sql("update ouf_udp.materialization_job set state='FAILED',state_version=state_version+1,claimed_by=null,lease_until=null,safe_failure_code=:c,updated_at=transaction_timestamp() where job_id=:j and state='RUNNING' and claimed_by=:w").param("c",safe(safeCode)).param("j",claim.jobId()).param("w",claim.worker()).update();db.sql("update ouf_udp.handoff_intake set state='FAILED',failure_code=:c where handoff_id=:h").param("c",safe(safeCode)).param("h",claim.handoffId()).update();event(claim.handoffId(),"RESOLUTION_FAILED",Map.of());}
  private void event(String handoff,String type,Map<String,Object> detail){db.sql("insert into ouf_udp.handoff_event(event_id,handoff_id,event_type,safe_detail) values(gen_random_uuid(),:h,:t,cast(:d as jsonb))").param("h",handoff).param("t",type).param("d",write(detail)).update();}
  private Map<String,Object> read(String value){try{return json.readValue(value,new TypeReference<>(){});}catch(Exception e){throw new IllegalStateException("UDP_STORED_JSON_INVALID",e);}}
  private String write(Object value){try{return json.writeValueAsString(value);}catch(Exception e){throw new IllegalStateException("UDP_STORED_JSON_INVALID",e);}}
  private static String safe(String value){return value!=null&&value.matches("UDP_[A-Z0-9_]{1,70}")?value:"UDP_RESOLUTION_FAILED";}
  public record Claim(UUID jobId,String handoffId,String typeCode,Map<String,Object> payload,String worker,String integrityBaselineHash,int integrityAttempts){}
}
