package it.comune.trieste.ouf.udp;

import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

@Service
public class SpatialQueryService {
  private final JdbcClient db;private final SpatialBudgetStore budgets;
  public SpatialQueryService(JdbcClient db,SpatialBudgetStore budgets){this.db=db;this.budgets=budgets;}

  @Transactional public Result nearby(UUID anchor,String targetType,double maxDistanceMeters,int maxResults,ServingAuthorizationContext auth){auth.require("urban.spatial.nearby");validateTypeAndLimit(targetType,maxResults);if(!(maxDistanceMeters>0&&maxDistanceMeters<=50000))throw new IllegalArgumentException("UDP_SPATIAL_RADIUS_OUT_OF_RANGE");ensureVisibleGeometry(anchor,auth);budgets.consume(auth,maxResults,maxResults*160L,1500,maxDistanceMeters,0);timeout();if(auth.allowedDataLabels().isEmpty())return empty("POSTGIS_NEARBY");var rows=db.sql("select o.urban_object_id,ST_Distance(a.geometry::geography,g.geometry::geography) distance_meters from ouf_udp.urban_geometry_current ac join ouf_udp.urban_geometry a on a.geometry_revision_id=ac.geometry_revision_id join ouf_udp.urban_geometry_current gc on true join ouf_udp.urban_geometry g on g.geometry_revision_id=gc.geometry_revision_id join ouf_udp.urban_object o on o.urban_object_id=gc.urban_object_id where ac.urban_object_id=:anchor and o.tenant_id=:tenant and o.canonical_type=:type and o.status='ACTIVE' and o.urban_object_id<>:anchor and g.access_label in (:labels) and ST_DWithin(a.geometry::geography,g.geometry::geography,:radius) order by distance_meters,o.urban_object_id limit :limit").param("anchor",anchor).param("tenant",auth.tenantId()).param("type",targetType).param("labels",auth.allowedDataLabels()).param("radius",maxDistanceMeters).param("limit",maxResults).query((rs,n)->new Hit(rs.getObject("urban_object_id",UUID.class),rs.getDouble("distance_meters"))).list();return new Result(rows,false,"POSTGIS_NEARBY");}

  @Transactional public Result envelope(String operation,double minLon,double minLat,double maxLon,double maxLat,String crs,String targetType,int maxResults,ServingAuthorizationContext auth){if(!Set.of("INTERSECTS","WITHIN").contains(operation))throw new IllegalArgumentException("UDP_SPATIAL_OPERATION_UNSUPPORTED");String capability="INTERSECTS".equals(operation)?"urban.spatial.intersects":"urban.spatial.within";auth.require(capability);validateTypeAndLimit(targetType,maxResults);if(!"EPSG:4326".equals(crs))throw new IllegalArgumentException("UDP_SPATIAL_CRS_UNSUPPORTED");double area=areaSqKm(minLon,minLat,maxLon,maxLat);if(!(area>0&&area<=2500))throw new IllegalArgumentException("UDP_SPATIAL_AREA_OUT_OF_RANGE");budgets.consume(auth,maxResults,maxResults*160L,1500,0,area);timeout();if(auth.allowedDataLabels().isEmpty())return empty("POSTGIS_"+operation);String predicate="INTERSECTS".equals(operation)?"ST_Intersects(g.geometry,e.box)":"ST_Within(g.geometry,e.box)";var rows=db.sql("with e as(select ST_MakeEnvelope(:minLon,:minLat,:maxLon,:maxLat,4326) box) select o.urban_object_id,cast(0 as float8) distance_meters from e join ouf_udp.urban_geometry_current gc on true join ouf_udp.urban_geometry g on g.geometry_revision_id=gc.geometry_revision_id join ouf_udp.urban_object o on o.urban_object_id=gc.urban_object_id where o.tenant_id=:tenant and o.canonical_type=:type and o.status='ACTIVE' and g.access_label in (:labels) and "+predicate+" order by o.urban_object_id limit :limit").param("minLon",minLon).param("minLat",minLat).param("maxLon",maxLon).param("maxLat",maxLat).param("tenant",auth.tenantId()).param("type",targetType).param("labels",auth.allowedDataLabels()).param("limit",maxResults).query((rs,n)->new Hit(rs.getObject("urban_object_id",UUID.class),rs.getDouble("distance_meters"))).list();return new Result(rows,false,"POSTGIS_"+operation);}

  @Transactional public Result intersectionSearch(UUID anchor,String targetType,int maxResults,ServingAuthorizationContext auth){auth.require("urban.spatial.intersection_search");validateTypeAndLimit(targetType,maxResults);ensureVisibleGeometry(anchor,auth);budgets.consume(auth,maxResults,maxResults*160L,1500,0,0);timeout();if(auth.allowedDataLabels().isEmpty())return empty("POSTGIS_INTERSECTION_SEARCH");var rows=db.sql("select o.urban_object_id,cast(0 as float8) distance_meters from ouf_udp.urban_geometry_current ac join ouf_udp.urban_geometry a on a.geometry_revision_id=ac.geometry_revision_id join ouf_udp.urban_geometry_current gc on true join ouf_udp.urban_geometry g on g.geometry_revision_id=gc.geometry_revision_id join ouf_udp.urban_object o on o.urban_object_id=gc.urban_object_id where ac.urban_object_id=:anchor and o.tenant_id=:tenant and o.canonical_type=:type and o.status='ACTIVE' and o.urban_object_id<>:anchor and g.access_label in (:labels) and ST_Intersects(g.geometry,a.geometry) order by o.urban_object_id limit :limit").param("anchor",anchor).param("tenant",auth.tenantId()).param("type",targetType).param("labels",auth.allowedDataLabels()).param("limit",maxResults).query((rs,n)->new Hit(rs.getObject("urban_object_id",UUID.class),rs.getDouble("distance_meters"))).list();return new Result(rows,false,"POSTGIS_INTERSECTION_SEARCH");}

  private void ensureVisibleGeometry(UUID id,ServingAuthorizationContext auth){if(auth.allowedDataLabels().isEmpty())throw notFound();long n=db.sql("select count(*) from ouf_udp.urban_object o join ouf_udp.urban_geometry_current c on c.urban_object_id=o.urban_object_id join ouf_udp.urban_geometry g on g.geometry_revision_id=c.geometry_revision_id where o.urban_object_id=:id and o.tenant_id=:tenant and g.access_label in (:labels)").param("id",id).param("tenant",auth.tenantId()).param("labels",auth.allowedDataLabels()).query(Long.class).single();if(n==0)throw notFound();}
  private static ResponseStatusException notFound(){return new ResponseStatusException(HttpStatus.NOT_FOUND,"UDP_SPATIAL_ANCHOR_NOT_VISIBLE");}
  private void timeout(){db.sql("set local statement_timeout='1500ms'").update();}
  private static void validateTypeAndLimit(String type,int limit){if(type==null||type.isBlank()||type.contains("*")||limit<1||limit>200)throw new IllegalArgumentException("UDP_SPATIAL_FILTER_OR_LIMIT_INVALID");}
  private static double areaSqKm(double minLon,double minLat,double maxLon,double maxLat){if(minLon< -180||maxLon>180||minLat< -90||maxLat>90||minLon>=maxLon||minLat>=maxLat)throw new IllegalArgumentException("UDP_SPATIAL_ENVELOPE_INVALID");double latKm=(maxLat-minLat)*111.32;double lonKm=(maxLon-minLon)*111.32*Math.cos(Math.toRadians((minLat+maxLat)/2));return latKm*lonKm;}
  private static Result empty(String plan){return new Result(List.of(),false,plan);}
  public record Hit(UUID urbanObjectId,double distanceMeters){}
  public record Result(List<Hit> hits,boolean truncated,String physicalPlan){public Result{hits=List.copyOf(hits);}}
}
