#!/usr/bin/env python3
"""Synthetic NTv2 fixture: constant +1 latitude/-2 longitude arcseconds. NOT A SURVEY GRID."""
import hashlib
import json
from pathlib import Path
import struct
import sys

root=Path(sys.argv[1]);root.mkdir(parents=True,exist_ok=True)
def record(name,value):
    if isinstance(value,int): raw=struct.pack('<i4x',value)
    elif isinstance(value,float): raw=struct.pack('<d',value)
    else: raw=value.encode('ascii').ljust(8,b' ')
    return name.encode('ascii').ljust(8,b' ')+raw
header=[('NUM_OREC',11),('NUM_SREC',11),('NUM_FILE',1),('GS_TYPE','SECONDS'),('VERSION','TEST1'),('SYSTEM_F','TESTSRC'),('SYSTEM_T','TESTDST'),('MAJOR_F',6378137.),('MINOR_F',6356752.314),('MAJOR_T',6378137.),('MINOR_T',6356752.314)]
sub=[('SUB_NAME','SYNTH'),('PARENT','NONE'),('CREATED','20260917'),('UPDATED','20260917'),('S_LAT',0.),('N_LAT',7200.),('E_LONG',-7200.),('W_LONG',0.),('LAT_INC',3600.),('LONG_INC',3600.),('GS_COUNT',9)]
content=b''.join(record(*r) for r in header+sub)+struct.pack('<ffff',1.,2.,-1.,-1.)*9+record('END',0.)
(root/'synthetic.gsb').write_bytes(content)
manifest={'schemaVersion':1,'grids':{'synthetic.gsb':hashlib.sha256(content).hexdigest()},'metadata':{'synthetic.gsb':{'version':'synthetic-1','licenseRef':'CC0-1.0; generated by this repository','provenanceRef':'scripts/ci/r2d-grid-fixture.py','areaOfUse':'TEST ONLY 0..2 degrees; no real datum validity'}}}
(root/'manifest.json').write_text(json.dumps(manifest,sort_keys=True,separators=(',',':'))+'\n')
print('Synthetic test resource generated; not suitable for municipal deployment')
