package it.comune.trieste.ouf.udp;

import static org.assertj.core.api.Assertions.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.web.server.ResponseStatusException;

@SpringBootTest
class GraphQueryRuntimeTest {
  @DynamicPropertySource static void database(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->required("OUF_UDP_DB_URL"));r.add("spring.datasource.username",()->required("OUF_UDP_DB_USER"));r.add("spring.datasource.password",()->required("OUF_UDP_DB_PASSWORD"));}
  @Autowired GraphQueryService graph;@Autowired RelatedSearchService related;@Autowired QueryBudgetStore budgets;@Autowired JdbcClient db;
  private ServingAuthorizationContext auth;
  @BeforeEach void clean(){db.sql("truncate table ouf_udp.capability_retry_guard,ouf_udp.query_budget,ouf_udp.serving_access_audit,ouf_udp.merge_resolution_issue,ouf_udp.merge_property_contribution_link,ouf_udp.human_resolution_decision,ouf_udp.split_resolution_issue,ouf_udp.relationship_identity_history,ouf_udp.source_binding_history,ouf_udp.object_identity_history,ouf_udp.governance_audit,ouf_udp.governance_plan,ouf_udp.spatial_resolution_issue,ouf_udp.urban_geometry_current,ouf_udp.urban_geometry,ouf_udp.relationship_issue,ouf_udp.relationship_revision,ouf_udp.relationship_contribution,ouf_udp.urban_relationship,ouf_udp.property_conflict,ouf_udp.property_value,ouf_udp.materialization_observation,ouf_udp.property_contribution,ouf_udp.object_revision,ouf_udp.resolution_issue,ouf_udp.resolution_decision,ouf_udp.source_binding,ouf_udp.urban_object,ouf_udp.materialization_job,ouf_udp.handoff_event,ouf_udp.handoff_intake restart identity cascade").update();auth=context("corr-graph");}
  @Test void neighborsIsOneHopBoundedAndFiltersRestrictedEdges(){UUID a=object(),b=object(),c=object();edge("e1",a,b,"ouf:child","OPEN");edge("e2",a,c,"ouf:child","RESTRICTED");var result=graph.neighbors(a,List.of("ouf:child"),10,10,auth);assertThat(result.edges()).hasSize(1);assertThat(result.nodes()).containsExactlyInAnyOrder(a,b).doesNotContain(c);assertThat(result.physicalPlan()).isEqualTo("INDEXED_ADJACENCY");}
  @Test void recursiveTraversalHonorsDepthAndUsesBackendPlan(){UUID a=object(),b=object(),c=object();edge("e1",a,b,"ouf:child","OPEN");edge("e2",b,c,"ouf:child","OPEN");var result=graph.traverse(a,List.of("ouf:child"),2,10,10,CapabilityRouter.TraversalPurpose.RECURSIVE_HIERARCHY,auth);assertThat(result.nodes()).containsExactlyInAnyOrder(a,b,c);assertThat(result.edges()).extracting(GraphQueryService.Edge::depth).containsExactly(1,2);assertThat(result.physicalPlan()).isEqualTo("BOUNDED_RECURSIVE_CTE");}
  @Test void tenantMismatchUsesAntiEnumerationNotFoundAndNoBudget(){UUID a=object();db.sql("update ouf_udp.urban_object set tenant_id='other' where urban_object_id=:id").param("id",a).update();assertThatThrownBy(()->graph.neighbors(a,List.of("ouf:child"),10,10,auth)).isInstanceOf(ResponseStatusException.class).hasMessageContaining("404").hasMessageNotContaining(a.toString());assertThat(db.sql("select count(*) from ouf_udp.query_budget").query(Long.class).single()).isZero();}
  @Test void misuseAndUnboundedRequestsAreRejectedBeforeQuery(){UUID a=object();assertThatThrownBy(()->graph.traverse(a,List.of("ouf:child"),5,10,10,CapabilityRouter.TraversalPurpose.RECURSIVE_HIERARCHY,auth)).hasMessageContaining("DEPTH");CapabilityMismatchException mismatch=catchThrowableOfType(()->graph.traverse(UUID.randomUUID(),List.of("ouf:child"),2,10,10,CapabilityRouter.TraversalPurpose.CROSS_DOMAIN_RELATIONSHIP,auth),CapabilityMismatchException.class);assertThat(mismatch.remediation().code()).isEqualTo("QUERY_CAPABILITY_MISMATCH");assertThat(mismatch.remediation().reason()).isEqualTo("CROSS_DOMAIN_NON_RECURSIVE_PATTERN");assertThat(mismatch.remediation().recommendedCapability()).isEqualTo("urban.object.related_search");assertThat(mismatch.remediation().reusableArguments()).contains("startObjectId","relationTypes");assertThat(mismatch.remediation().missingArguments()).contains("anchorType","targetTypes","direction");assertThat(mismatch.remediation().recommendedArgumentShapeRef()).isEqualTo("capability://urban.object.related_search/input-schema");assertThat(mismatch.remediation().budgetImpact()).isEqualTo(new CapabilityRouter.BudgetImpact("NONE","ONE_MISMATCH"));Map<String,Object> budget=db.sql("select mismatch_calls,query_calls,nodes_observed,edges_observed,db_time_ms from ouf_udp.query_budget").query().singleRow();assertThat(budget.get("mismatch_calls")).isEqualTo(1);assertThat(((Number)budget.get("query_calls")).longValue()).isZero();assertThat(((Number)budget.get("nodes_observed")).longValue()).isZero();assertThat(((Number)budget.get("edges_observed")).longValue()).isZero();assertThat(((Number)budget.get("db_time_ms")).longValue()).isZero();}
  @Test void cumulativeBudgetCannotBeResetAcrossCalls(){budgets.consume(auth,"GRAPH",1,1200,10,100,100);assertThatThrownBy(()->budgets.consume(auth,"GRAPH",1,1200,10,100,100)).isInstanceOf(ResponseStatusException.class).hasMessageContaining("429");}
  @Test void specialistRetryIsExplicitAuthorizedAndUsesSameCorrelationBudget(){UUID street=object(),dehor=object();db.sql("update ouf_udp.urban_object set canonical_type='ouf:Street' where urban_object_id=:id").param("id",street).update();db.sql("update ouf_udp.urban_object set canonical_type='ouf:Dehor' where urban_object_id=:id").param("id",dehor).update();edge("related-edge",dehor,street,"ouf:locatedOn","OPEN");assertThatThrownBy(()->graph.traverse(street,List.of("ouf:locatedOn"),2,10,10,CapabilityRouter.TraversalPurpose.CROSS_DOMAIN_RELATIONSHIP,auth)).isInstanceOf(CapabilityMismatchException.class);var request=new RelatedSearchService.Request(street,"ouf:Street","ouf:locatedOn",RelatedSearchService.Direction.INBOUND,List.of("ouf:Dehor"),10);assertThatThrownBy(()->related.search(request,auth)).isInstanceOf(SecurityException.class);ServingAuthorizationContext specialist=new ServingAuthorizationContext("AI_AGENT","agent","default",Set.of("urban.object.related_search"),Set.of("OPEN","ANONYMOUS"),"authz://graph","corr-graph");assertThat(related.search(request,specialist).hits()).extracting(RelatedSearchService.Hit::urbanObjectId).containsExactly(dehor);Map<String,Object> budget=db.sql("select mismatch_calls,query_calls from ouf_udp.query_budget where correlation_id='corr-graph'").query().singleRow();assertThat(budget.get("mismatch_calls")).isEqualTo(1);assertThat(budget.get("query_calls")).isEqualTo(1);}
  @Test void equivalentRetriesStallAtConfiguredThresholdAndSubstantiveChangeProgresses(){UUID anchor=UUID.randomUUID();assertThatThrownBy(()->graph.traverse(anchor,List.of("ouf:b","ouf:a"),2,10,10,CapabilityRouter.TraversalPurpose.CROSS_DOMAIN_RELATIONSHIP,auth)).isInstanceOf(CapabilityMismatchException.class);assertThatThrownBy(()->graph.traverse(anchor,List.of("ouf:a","ouf:b","ouf:a"),4,500,1000,CapabilityRouter.TraversalPurpose.CROSS_DOMAIN_RELATIONSHIP,auth)).isInstanceOf(CapabilityMismatchException.class);ToolSelectionStalledException stalled=catchThrowableOfType(()->graph.traverse(anchor,List.of("ouf:a","ouf:b"),1,1,1,CapabilityRouter.TraversalPurpose.CROSS_DOMAIN_RELATIONSHIP,auth),ToolSelectionStalledException.class);assertThat(stalled.response().attempts()).isEqualTo(3);assertThat(stalled.response().threshold()).isEqualTo(3);assertThat(stalled.response().retryable()).isFalse();assertThat(stalled.response().governedActions()).contains("ASK_USER_CLARIFICATION","STOP");assertThatThrownBy(()->graph.traverse(anchor,List.of("ouf:b","ouf:a"),2,10,10,CapabilityRouter.TraversalPurpose.CROSS_DOMAIN_RELATIONSHIP,auth)).isInstanceOf(ToolSelectionStalledException.class);assertThatThrownBy(()->graph.traverse(UUID.randomUUID(),List.of("ouf:a","ouf:b"),2,10,10,CapabilityRouter.TraversalPurpose.CROSS_DOMAIN_RELATIONSHIP,auth)).isInstanceOf(CapabilityMismatchException.class);List<Map<String,Object>> guards=db.sql("select attempt_count,state from ouf_udp.capability_retry_guard order by attempt_count desc").query().listOfRows();assertThat(guards).hasSize(2);assertThat(guards.getFirst().get("attempt_count")).isEqualTo(3);assertThat(guards.getFirst().get("state")).isEqualTo("STALLED");assertThat(db.sql("select mismatch_calls from ouf_udp.query_budget where correlation_id='corr-graph'").query(Integer.class).single()).isEqualTo(3);}
  @Test void compositeAnalyticsIsRejectedBeforeLookupPlannerOrServingSql(){UUID missing=UUID.randomUUID();AnalyticalCapabilityRequiredException required=catchThrowableOfType(()->graph.traverse(missing,List.of("ouf:locatedOn"),4,500,1000,CapabilityRouter.TraversalPurpose.ANALYTICAL_COMPOSITE,auth),AnalyticalCapabilityRequiredException.class);assertThat(required.response().code()).isEqualTo("QUERY_REQUIRES_ANALYTICAL_CAPABILITY");assertThat(required.response().requiredCapabilityClass()).isEqualTo("ANALYTICAL_OR_GOVERNED_ASYNC_JOB");assertThat(required.response().asynchronousJobAvailable()).isFalse();assertThat(required.response().retryable()).isFalse();assertThat(required.response().governedActions()).contains("NARROW_TO_OPERATIONAL_QUERY","STOP");assertThat(required.response().budgetImpact()).isEqualTo(new CapabilityRouter.BudgetImpact("NONE","ONE_ANALYTICAL_REJECTION"));Map<String,Object> budget=db.sql("select mismatch_calls,query_calls,nodes_observed,edges_observed,db_time_ms from ouf_udp.query_budget where correlation_id='corr-graph'").query().singleRow();assertThat(budget.get("mismatch_calls")).isEqualTo(1);assertThat(((Number)budget.get("query_calls")).longValue()).isZero();assertThat(((Number)budget.get("nodes_observed")).longValue()).isZero();assertThat(((Number)budget.get("edges_observed")).longValue()).isZero();assertThat(((Number)budget.get("db_time_ms")).longValue()).isZero();assertThat(db.sql("select count(*) from ouf_udp.capability_retry_guard").query(Long.class).single()).isZero();}
  @Test void concurrentBudgetConsumptionIsRaceSafe() throws Exception {ServingAuthorizationContext shared=context("corr-race");AtomicInteger accepted=new AtomicInteger();try(ExecutorService pool=Executors.newFixedThreadPool(2)){List<Callable<Void>> calls=List.of(()->{consume(shared,accepted);return null;},()->{consume(shared,accepted);return null;});for(Future<Void> f:pool.invokeAll(calls))f.get();}assertThat(accepted).hasValue(1);assertThat(db.sql("select nodes_observed from ouf_udp.query_budget where correlation_id='corr-race'").query(Long.class).single()).isEqualTo(1200);}
  private void consume(ServingAuthorizationContext c,AtomicInteger accepted){try{budgets.consume(c,"GRAPH",1,1200,10,100,100);accepted.incrementAndGet();}catch(ResponseStatusException ignored){}}
  private UUID object(){UUID id=UUID.randomUUID();db.sql("insert into ouf_udp.urban_object(urban_object_id,canonical_type,canonical_key,match_key) values(:i,'ouf:Node',:k,:k)").param("i",id).param("k",id.toString()).update();return id;}
  private void edge(String handoff,UUID source,UUID target,String relation,String label){db.sql("insert into ouf_udp.handoff_intake(handoff_id,ingestion_run_id,ingestion_id,source_id,type_code,source_object_id,content_hash,payload_json,receipt_ref) values(:h,'run','ing','graph','NODE',:h,:h,'{}',:r)").param("h",handoff).param("r","udp://"+handoff).update();UUID contribution=UUID.randomUUID(),relationship=UUID.randomUUID(),revision=UUID.randomUUID();db.sql("insert into ouf_udp.relationship_contribution(contribution_id,handoff_id,source_object_id,relation_iri,source_value,source_value_hash,strategy_ref,policy_ref,access_label,provenance_json) values(:i,:h,:s,:r,'{}',:h,'MANUAL','policy://graph',:l,'{}')").param("i",contribution).param("h",handoff).param("s",source).param("r",relation).param("l",label).update();db.sql("insert into ouf_udp.urban_relationship(relationship_id,source_object_id,relation_iri,target_object_id) values(:i,:s,:r,:t)").param("i",relationship).param("s",source).param("r",relation).param("t",target).update();db.sql("insert into ouf_udp.relationship_revision(relationship_revision_id,relationship_id,revision_no,contribution_id,evidence_hash,resolution_evidence,access_label) values(:i,:r,1,:c,:h,'{}',:l)").param("i",revision).param("r",relationship).param("c",contribution).param("h","hash-"+handoff).param("l",label).update();db.sql("update ouf_udp.urban_relationship set current_revision_id=:v where relationship_id=:r").param("v",revision).param("r",relationship).update();}
  private static ServingAuthorizationContext context(String correlation){return new ServingAuthorizationContext("AI_AGENT","agent","default",Set.of("urban.graph.neighbors","urban.graph.traverse"),Set.of("OPEN","ANONYMOUS"),"authz://graph",correlation);}
  private static String required(String n){String v=System.getenv(n);if(v==null)throw new IllegalStateException(n+" required");return v;}
}
