package it.comune.trieste.ouf.udp;

import static org.assertj.core.api.Assertions.assertThat;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.file.*;
import java.time.Instant;
import java.util.*;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

@SpringBootTest
class PerformanceBaselineIT {
  private static final int WARMUP=5,PIPELINE_RUNS=30,QUERY_RUNS=40;
  @DynamicPropertySource static void database(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->required("OUF_UDP_DB_URL"));r.add("spring.datasource.username",()->required("OUF_UDP_DB_USER"));r.add("spring.datasource.password",()->required("OUF_UDP_DB_PASSWORD"));r.add("ouf.udp.lake.required",()->false);r.add("ouf.udp.lake.shadow.initial-delay-ms",()->3600000);r.add("ouf.udp.lake.maintenance.initial-delay-ms",()->3600000);}
  @Autowired HandoffIntakeService intake;@Autowired ObjectResolutionService resolution;@Autowired CanonicalMaterializer materializer;@Autowired GovernedServingService serving;@Autowired SpatialQueryService spatial;@Autowired JdbcClient db;@Autowired ObjectMapper json;
  private final UdpPorts.ResolutionProfile resolutionProfile=new UdpPorts.ResolutionProfile("CANONICAL_KEY","1","policy://perf-resolution/1","ouf:PerfRoad","code","code");
  private final UdpPorts.MaterializationProfile materializationProfile=new UdpPorts.MaterializationProfile("policy://perf-authority/1",List.of(new UdpPorts.PropertyRule("name","ouf:name","string","OPEN",List.of("perf")),new UdpPorts.PropertyRule("surface","ouf:surface","number","OPEN",List.of("perf"))));

  @Test void reproduciblePerformanceGate() throws Exception {
    seedQueries();List<Long> intakeNs=new ArrayList<>(),resolutionNs=new ArrayList<>(),materializationNs=new ArrayList<>(),servingNs=new ArrayList<>(),spatialNs=new ArrayList<>();
    for(int i=0;i<WARMUP+PIPELINE_RUNS;i++){Map<String,Object> payload=handoff("perf-h-"+i,"perf-o-"+i,"P"+i);long a=System.nanoTime();intake.accept(payload);long b=System.nanoTime();var decision=resolution.resolve("perf-h-"+i,payload,resolutionProfile);long c=System.nanoTime();materializer.materialize("perf-h-"+i,decision.targetUrbanObjectId(),payload,materializationProfile);long d=System.nanoTime();if(i>=WARMUP){intakeNs.add(b-a);resolutionNs.add(c-b);materializationNs.add(d-c);}}
    var servingAuth=auth("urban.object.search","perf-serving");for(int i=0;i<WARMUP+QUERY_RUNS;i++){long a=System.nanoTime();var page=serving.search("ouf:PerfSearch",100,null,servingAuth);long b=System.nanoTime();assertThat(page.items()).hasSize(100);if(i>=WARMUP)servingNs.add(b-a);}
    UUID anchor=db.sql("select urban_object_id from ouf_udp.urban_object where canonical_type='ouf:PerfSpatial' order by urban_object_id limit 1").query(UUID.class).single();for(int i=0;i<WARMUP+QUERY_RUNS;i++){long a=System.nanoTime();var result=spatial.nearby(anchor,"ouf:PerfSpatial",20000,100,auth("urban.spatial.nearby","perf-spatial-"+i));long b=System.nanoTime();assertThat(result.hits()).isNotEmpty();if(i>=WARMUP)spatialNs.add(b-a);}
    Map<String,Metric> metrics=new LinkedHashMap<>();metrics.put("intake",metric(intakeNs,100));metrics.put("resolution",metric(resolutionNs,100));metrics.put("materialization",metric(materializationNs,250));metrics.put("serving_search_5000",metric(servingNs,100));metrics.put("spatial_nearby_2000",metric(spatialNs,300));writeEvidence(metrics);metrics.forEach((name,value)->assertThat(value.p95Ms()).as(name+" p95 threshold").isLessThanOrEqualTo(value.thresholdMs()));
  }

  private void seedQueries(){db.sql("insert into ouf_udp.urban_object(urban_object_id,canonical_type,canonical_key,match_key,tenant_id) select gen_random_uuid(),'ouf:PerfSearch','search-'||g,'search-'||g,'default' from generate_series(1,5000) g").update();db.sql("insert into ouf_udp.urban_object(urban_object_id,canonical_type,canonical_key,match_key,tenant_id) select gen_random_uuid(),'ouf:PerfSpatial','spatial-'||g,'spatial-'||g,'default' from generate_series(1,2000) g").update();db.sql("insert into ouf_udp.handoff_intake(handoff_id,ingestion_run_id,ingestion_id,source_id,type_code,source_object_id,content_hash,payload_json,receipt_ref) select 'perf-spatial-'||urban_object_id,'perf-run','perf-ing','perf','SPATIAL',urban_object_id::text,'sha256:'||urban_object_id,'{}','udp://perf/'||urban_object_id from ouf_udp.urban_object where canonical_type='ouf:PerfSpatial'").update();db.sql("insert into ouf_udp.urban_geometry(geometry_revision_id,urban_object_id,handoff_id,geometry,geometry_hash,source_crs,canonical_srid,normalization_version,access_label,evidence_json) select gen_random_uuid(),urban_object_id,'perf-spatial-'||urban_object_id,ST_SetSRID(ST_MakePoint(13.70+(row_number() over(order by urban_object_id)%100)*0.001,45.60+(row_number() over(order by urban_object_id)%100)*0.001),4326),'sha256:'||urban_object_id,'EPSG:4326',4326,'perf-v1','OPEN','{}' from ouf_udp.urban_object where canonical_type='ouf:PerfSpatial'").update();db.sql("insert into ouf_udp.urban_geometry_current(urban_object_id,geometry_revision_id) select urban_object_id,geometry_revision_id from ouf_udp.urban_geometry where handoff_id like 'perf-spatial-%'").update();db.sql("analyze ouf_udp.urban_object").update();db.sql("analyze ouf_udp.urban_geometry").update();}
  private void writeEvidence(Map<String,Metric> metrics)throws Exception{Path dir=Path.of("target/performance-evidence");Files.createDirectories(dir);Map<String,Object> report=new LinkedHashMap<>();report.put("result",metrics.values().stream().allMatch(x->x.p95Ms()<=x.thresholdMs())?"PASS":"FAIL");report.put("measuredAt",Instant.now().toString());report.put("javaVersion",System.getProperty("java.version"));report.put("postgresVersion",db.sql("show server_version").query(String.class).single());report.put("runnerProcessors",Runtime.getRuntime().availableProcessors());report.put("warmupIterations",WARMUP);report.put("pipelineMeasuredIterations",PIPELINE_RUNS);report.put("queryMeasuredIterations",QUERY_RUNS);report.put("dataset",Map.of("servingObjects",5000,"spatialObjects",2000));report.put("metrics",metrics);json.writerWithDefaultPrettyPrinter().writeValue(dir.resolve("PERFORMANCE_RESULT.json").toFile(),report);StringBuilder md=new StringBuilder("# UDP reproducible performance baseline\n\nResult: **").append(report.get("result")).append("**\n\n| Workload | p50 ms | p95 ms | max ms | threshold p95 ms | ops/s |\n|---|---:|---:|---:|---:|---:|\n");metrics.forEach((n,m)->md.append('|').append(n).append('|').append(m.p50Ms()).append('|').append(m.p95Ms()).append('|').append(m.maxMs()).append('|').append(m.thresholdMs()).append('|').append(m.opsPerSecond()).append("|\n"));Files.writeString(dir.resolve("PERFORMANCE_RESULT.md"),md);}
  private static Metric metric(List<Long> values,long threshold){List<Long> sorted=values.stream().sorted().toList();double total=values.stream().mapToLong(Long::longValue).sum()/1_000_000_000d;return new Metric(ms(sorted.get((int)Math.ceil(sorted.size()*.50)-1)),ms(sorted.get((int)Math.ceil(sorted.size()*.95)-1)),ms(sorted.getLast()),threshold,round(values.size()/total),sorted.stream().map(PerformanceBaselineIT::ms).toList());}
  private static double ms(long ns){return round(ns/1_000_000d);}private static double round(double v){return Math.round(v*100d)/100d;}
  private static ServingAuthorizationContext auth(String capability,String correlation){return new ServingAuthorizationContext("AI_AGENT","perf-agent","default",Set.of(capability),Set.of("OPEN","ANONYMOUS"),"authz://performance",correlation);}
  private static Map<String,Object> handoff(String id,String object,String code){return new LinkedHashMap<>(Map.ofEntries(Map.entry("handoffId",id),Map.entry("ingestionRunId","perf-run"),Map.entry("ingestionId","ing-"+id),Map.entry("sourceIdentity",new LinkedHashMap<>(Map.of("sourceId","perf","typeCode","PERF_ROAD","sourceObjectId",object,"observedAt","2026-09-13T00:00:00Z"))),Map.entry("operation","UPSERT"),Map.entry("canonicalPayload",Map.of("code",code,"name","Road "+code,"surface",42)),Map.entry("rawObjectRef","raw://"+id),Map.entry("contractRefs",Map.of("sourceSchemaRef","schema://perf/1","bundleRef","bundle://perf/1","semanticPublicationSetRef","semantic://perf/1","adapterProfileRef","adapter://perf/1")),Map.entry("lineageId","lineage-"+id),Map.entry("contentHash","sha256:"+id),Map.entry("acquiredAt","2026-09-13T00:00:00Z"),Map.entry("changeRepresentation",Map.of("mode","FULL_SNAPSHOT"))));}
  private static String required(String n){String v=System.getenv(n);if(v==null)throw new IllegalStateException(n+" required");return v;}
  record Metric(double p50Ms,double p95Ms,double maxMs,long thresholdMs,double opsPerSecond,List<Double> sortedSamplesMs){}
}
