package it.comune.trieste.ouf.udp;

import static org.assertj.core.api.Assertions.*;
import java.time.OffsetDateTime;
import java.util.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;

@SpringBootTest
class TemporalDeltaRuntimeTest {
  @DynamicPropertySource static void database(DynamicPropertyRegistry r){r.add("spring.datasource.url",()->required("OUF_UDP_DB_URL"));r.add("spring.datasource.username",()->required("OUF_UDP_DB_USER"));r.add("spring.datasource.password",()->required("OUF_UDP_DB_PASSWORD"));r.add("ouf.udp.lake.required",()->"false");}
  @Autowired HandoffIntakeService intake;@Autowired ObjectResolutionService resolution;@Autowired CanonicalMaterializer materializer;@Autowired CanonicalRevisionReconstructor reconstructor;@Autowired JdbcClient db;
  private final UdpPorts.ResolutionProfile resolutionProfile=new UdpPorts.ResolutionProfile("CANONICAL_KEY","1","policy://resolution/1","ouf:Road","code","code");
  private final List<UdpPorts.PropertyRule> rules=List.of(new UdpPorts.PropertyRule("name","ouf:name","string","OPEN",List.of("registry")),new UdpPorts.PropertyRule("surface","ouf:surface","number","OPEN",List.of("registry")));
  @BeforeEach void clean(){db.sql("truncate table ouf_udp.property_bitemporal_interval,ouf_udp.urban_object_current_state,ouf_udp.property_conflict,ouf_udp.property_value,ouf_udp.materialization_observation,ouf_udp.property_contribution,ouf_udp.object_revision,ouf_udp.resolution_issue,ouf_udp.resolution_decision,ouf_udp.source_binding,ouf_udp.urban_object,ouf_udp.materialization_job,ouf_udp.handoff_event,ouf_udp.handoff_intake restart identity cascade").update();}

  @Test void deltaRevisionAvoidsFullPayloadDuplicationAndReconstructsFromCheckpoint(){
    var profile=new UdpPorts.MaterializationProfile("policy://authority/1",rules,Set.of(),4);Map<String,Object> first=full("delta-1","Road One",10,"2026-01-01T00:00:00Z",null);UUID object=resolved(first);var checkpoint=materializer.materialize("delta-1",object,first,profile);String baseHash=db.sql("select canonical_hash from ouf_udp.object_revision where revision_id=:r").param("r",checkpoint.revisionId()).query(String.class).single();Map<String,Object> patch=delta("delta-2",Map.of("surface",11),checkpoint.revisionId(),baseHash);intake.accept(patch);var changed=materializer.materialize("delta-2",object,patch,profile);
    Map<String,Object> stored=db.sql("select representation,canonical_payload,canonical_delta::text delta,base_revision_id from ouf_udp.object_revision where revision_id=:r").param("r",changed.revisionId()).query().singleRow();assertThat(stored.get("representation")).isEqualTo("DELTA_PATCH");assertThat(stored.get("canonical_payload")).isNull();assertThat(stored.get("base_revision_id")).isEqualTo(checkpoint.revisionId());assertThat(String.valueOf(stored.get("delta"))).contains("ouf:surface","11").doesNotContain("Road One");assertThat(reconstructor.reconstruct(changed.revisionId())).containsEntry("ouf:name","Road One").containsEntry("ouf:surface",11);
  }

  @Test void bitemporalIntervalsExistOnlyForConfiguredPropertyAndPreserveRetroactiveCorrection(){
    var profile=new UdpPorts.MaterializationProfile("policy://authority/bitemporal",rules,Set.of("ouf:name"),1);Map<String,Object> first=full("time-1","Original",10,"2026-01-01T00:00:00Z",null);UUID object=resolved(first);materializer.materialize("time-1",object,first,profile);Map<String,Object> correction=full("time-2","Corrected",10,"2025-12-01T00:00:00Z",null);intake.accept(correction);materializer.materialize("time-2",object,correction,profile);
    List<Map<String,Object>> rows=db.sql("select property_iri,valid_from,system_from,system_to from ouf_udp.property_bitemporal_interval order by system_from,interval_id").query().listOfRows();assertThat(rows).hasSize(2).allMatch(r->"ouf:name".equals(r.get("property_iri")));assertThat(rows.getFirst().get("system_to")).isNotNull();assertThat(rows.getLast().get("system_to")).isNull();assertThat(rows.getLast().get("valid_from")).isEqualTo(OffsetDateTime.parse("2025-12-01T00:00:00Z"));assertThat(db.sql("select count(*) from ouf_udp.property_bitemporal_interval where property_iri='ouf:surface'").query(Long.class).single()).isZero();Map<String,Object> evidence=db.sql("select observed_at,recorded_at from ouf_udp.object_revision order by revision_no desc limit 1").query().singleRow();assertThat(evidence.get("observed_at")).isNotNull();assertThat(evidence.get("recorded_at")).isNotNull();
  }

  @Test void completeFingerprintsSkipPreviousPayloadParsingForIdenticalObservation(){
    var profile=new UdpPorts.MaterializationProfile("policy://authority/1",rules);Map<String,Object> first=full("fast-1","Stable",10,"2026-01-01T00:00:00Z",fingerprints());UUID object=resolved(first);var initial=materializer.materialize("fast-1",object,first,profile);db.sql("update ouf_udp.urban_object_current_state set canonical_payload='42'::jsonb where urban_object_id=:u").param("u",object).update();Map<String,Object> same=full("fast-2","payload must not be parsed",999,"2026-01-01T00:00:00Z",fingerprints());intake.accept(same);var unchanged=materializer.materialize("fast-2",object,same,profile);assertThat(unchanged.materialChange()).isFalse();assertThat(unchanged.revisionId()).isEqualTo(initial.revisionId());assertThat(db.sql("select count(*) from ouf_udp.object_revision where urban_object_id=:u").param("u",object).query(Long.class).single()).isOne();assertThat(db.sql("select count(*) from ouf_udp.materialization_observation where urban_object_id=:u").param("u",object).query(Long.class).single()).isEqualTo(2);
  }

  @Test void deltaWithWrongBaseIsRejectedWithoutRevision(){Map<String,Object> first=full("base-1","Road",10,"2026-01-01T00:00:00Z",null);UUID object=resolved(first);var profile=new UdpPorts.MaterializationProfile("policy://authority/1",rules,Set.of(),4);materializer.materialize("base-1",object,first,profile);Map<String,Object> patch=delta("base-2",Map.of("surface",12),UUID.randomUUID(),"sha256:"+"0".repeat(64));intake.accept(patch);assertThatThrownBy(()->materializer.materialize("base-2",object,patch,profile)).hasMessage("UDP_DELTA_BASE_MISMATCH");assertThat(db.sql("select count(*) from ouf_udp.object_revision where urban_object_id=:u").param("u",object).query(Long.class).single()).isOne();}

  private UUID resolved(Map<String,Object> handoff){intake.accept(handoff);return resolution.resolve(String.valueOf(handoff.get("handoffId")),handoff,resolutionProfile).targetUrbanObjectId();}
  private static Map<String,Object> full(String id,String name,int surface,String validFrom,Map<String,Object> fingerprints){Map<String,Object> source=new LinkedHashMap<>(Map.of("sourceId","registry","typeCode","ROAD","sourceObjectId","road-1","observedAt","2026-02-03T11:42:00Z","validFrom",validFrom));Map<String,Object> change=new LinkedHashMap<>(Map.of("mode","FULL_SNAPSHOT"));if(fingerprints!=null)change.putAll(fingerprints);return envelope(id,source,Map.of("code","R1","name",name,"surface",surface),change);}
  private static Map<String,Object> delta(String id,Map<String,Object> patch,UUID base,String hash){Map<String,Object> source=new LinkedHashMap<>(Map.of("sourceId","registry","typeCode","ROAD","sourceObjectId","road-1","observedAt","2026-02-04T11:42:00Z"));return envelope(id,source,patch,Map.of("mode","DELTA_PATCH","baseRevisionRef","revision://"+base,"baseContentHash",hash));}
  private static Map<String,Object> envelope(String id,Map<String,Object> source,Map<String,Object> payload,Map<String,Object> change){return new LinkedHashMap<>(Map.ofEntries(Map.entry("handoffId",id),Map.entry("ingestionRunId","run-"+id),Map.entry("ingestionId","ing-"+id),Map.entry("sourceIdentity",source),Map.entry("operation","UPSERT"),Map.entry("canonicalPayload",payload),Map.entry("rawObjectRef","raw://"+id),Map.entry("contractRefs",Map.of("sourceSchemaRef","schema://road/1","bundleRef","bundle://road/1","semanticPublicationSetRef","semantic://publication/1","adapterProfileRef","adapter://rest/1")),Map.entry("lineageId","lineage-"+id),Map.entry("contentHash","sha256:"+id),Map.entry("acquiredAt","2026-02-03T11:42:04Z"),Map.entry("changeRepresentation",change)));}
  private static Map<String,Object> fingerprints(){return Map.of("canonicalContentHash","sha256:canonical","geometryHash","sha256:geometry","relationshipsHash","sha256:relationships","contractEvidenceHash","sha256:contract");}
  private static String required(String n){String v=System.getenv(n);if(v==null)throw new IllegalStateException(n+" required");return v;}
}
